In [15]:
import pandas as pd

In [16]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/서울월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)

In [17]:
df

            지역  누적확진자
날짜
2020-02-01  서울     77
2020-03-01  서울    450
2020-04-01  서울    633
2020-05-01  서울    861
2020-06-01  서울   1312
2020-07-01  서울   1600
2020-08-01  서울   3867
2020-09-01  서울   5293
2020-10-01  서울   6011
2020-11-01  서울   8812
2020-12-01  서울  18996
2021-01-01  서울  24156
2021-02-01  서울  28236
2021-03-01  서울  32030
2021-04-01  서울  37837
2021-05-01  서울  43196
2021-06-01  서울  49987

In [18]:
df['서울월별확진자']=df['누적확진자'].diff()

In [19]:
df

            지역  누적확진자  서울월별확진자
날짜
2020-02-01  서울     77      NaN
2020-03-01  서울    450    373.0
2020-04-01  서울    633    183.0
2020-05-01  서울    861    228.0
2020-06-01  서울   1312    451.0
2020-07-01  서울   1600    288.0
2020-08-01  서울   3867   2267.0
2020-09-01  서울   5293   1426.0
2020-10-01  서울   6011    718.0
2020-11-01  서울   8812   2801.0
2020-12-01  서울  18996  10184.0
2021-01-01  서울  24156   5160.0
2021-02-01  서울  28236   4080.0
2021-03-01  서울  32030   3794.0
2021-04-01  서울  37837   5807.0
2021-05-01  서울  43196   5359.0
2021-06-01  서울  49987   6791.0

In [20]:
df.fillna(0, inplace=True)

In [21]:
df['서울월별확진자'] = df['서울월별확진자'].astype(int)

In [22]:
df

            지역  누적확진자  서울월별확진자
날짜
2020-02-01  서울     77        0
2020-03-01  서울    450      373
2020-04-01  서울    633      183
2020-05-01  서울    861      228
2020-06-01  서울   1312      451
2020-07-01  서울   1600      288
2020-08-01  서울   3867     2267
2020-09-01  서울   5293     1426
2020-10-01  서울   6011      718
2020-11-01  서울   8812     2801
2020-12-01  서울  18996    10184
2021-01-01  서울  24156     5160
2021-02-01  서울  28236     4080
2021-03-01  서울  32030     3794
2021-04-01  서울  37837     5807
2021-05-01  서울  43196     5359
2021-06-01  서울  49987     6791

In [23]:
df.to_csv('confirmed-month/서울월별확진자수.csv', sep=',')

In [24]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/경기월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['경기월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['경기월별확진자'] = df['경기월별확진자'].astype(int)
df.to_csv('confirmed-month/경기월별확진자수.csv', sep=',')

In [25]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/부산월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['부산월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['부산월별확진자'] = df['부산월별확진자'].astype(int)
df.to_csv('confirmed-month/부산월별확진자수.csv', sep=',')

In [26]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/대구월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['인천월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['인천월별확진자'] = df['인천월별확진자'].astype(int)
df.to_csv('confirmed-month/인천월별확진자수.csv', sep=',')

In [27]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/광주월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['광주월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['광주월별확진자'] = df['광주월별확진자'].astype(int)
df.to_csv('confirmed-month/광주월별확진자수.csv', sep=',')

In [28]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/울산월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['울산월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['울산월별확진자'] = df['울산월별확진자'].astype(int)
df.to_csv('confirmed-month/울산월별확진자수.csv', sep=',')

In [29]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/대전월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['대전월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['대전월별확진자'] = df['대전월별확진자'].astype(int)
df.to_csv('confirmed-month/대전월별확진자수.csv', sep=',')

In [30]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/세종월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['세종월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['세종월별확진자'] = df['세종월별확진자'].astype(int)
df.to_csv('confirmed-month/세종월별확진자수.csv', sep=',')

In [31]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/경북월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['경북월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['경북월별확진자'] = df['경북월별확진자'].astype(int)
df.to_csv('confirmed-month/경북월별확진자수.csv', sep=',')

In [32]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/경남월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['경남월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['경남월별확진자'] = df['경남월별확진자'].astype(int)
df.to_csv('confirmed-month/경남월별확진자수.csv', sep=',')

In [33]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/충북월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['충북월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['충북월별확진자'] = df['충북월별확진자'].astype(int)
df.to_csv('confirmed-month/충북월별확진자수.csv', sep=',')

In [34]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/충남월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['충남월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['충남월별확진자'] = df['충남월별확진자'].astype(int)
df.to_csv('confirmed-month/충남월별확진자수.csv', sep=',')

In [35]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/강원월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['강원월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['강원월별확진자'] = df['강원월별확진자'].astype(int)
df.to_csv('confirmed-month/강원월별확진자수.csv', sep=',')

In [36]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/전북월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['전북월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['전북월별확진자'] = df['전북월별확진자'].astype(int)
df.to_csv('confirmed-month/전북월별확진자수.csv', sep=',')

In [37]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/전남월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['전남월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['전남월별확진자'] = df['전남월별확진자'].astype(int)
df.to_csv('confirmed-month/전남월별확진자수.csv', sep=',')

In [38]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/제주월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['제주월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['제주월별확진자'] = df['제주월별확진자'].astype(int)
df.to_csv('confirmed-month/제주월별확진자수.csv', sep=',')

In [39]:
# 데이터파일 읽어오기 지역별,월별 코로나 확진자수
df = pd.read_csv('confirmed-month/대구월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df['대구월별확진자']=df['누적확진자'].diff()
df.fillna(0, inplace=True)
df['대구월별확진자'] = df['대구월별확진자'].astype(int)
df.to_csv('confirmed-month/대구월별확진자수.csv', sep=',')

In [40]:
df

            지역  누적확진자  대구월별확진자
날짜
2020-02-01  대구   2236        0
2020-03-01  대구   6684     4448
2020-04-01  대구   6852      168
2020-05-01  대구   6883       31
2020-06-01  대구   6906       23
2020-07-01  대구   6940       34
2020-08-01  대구   7047      107
2020-09-01  대구   7132       85
2020-10-01  대구   7174       42
2020-11-01  대구   7232       58
2020-12-01  대구   7801      569
2021-01-01  대구   8308      507
2021-02-01  대구   8623      315
2021-03-01  대구   8927      304
2021-04-01  대구   9351      424
2021-05-01  대구   9916      565
2021-06-01  대구  10598      682

In [43]:
df=df.replace(0, df['누적확진자']['2020-02-01'])

In [44]:
df

            지역  누적확진자  대구월별확진자
날짜
2020-02-01  대구   2236     2236
2020-03-01  대구   6684     4448
2020-04-01  대구   6852      168
2020-05-01  대구   6883       31
2020-06-01  대구   6906       23
2020-07-01  대구   6940       34
2020-08-01  대구   7047      107
2020-09-01  대구   7132       85
2020-10-01  대구   7174       42
2020-11-01  대구   7232       58
2020-12-01  대구   7801      569
2021-01-01  대구   8308      507
2021-02-01  대구   8623      315
2021-03-01  대구   8927      304
2021-04-01  대구   9351      424
2021-05-01  대구   9916      565
2021-06-01  대구  10598      682

In [45]:
df.to_csv('confirmed-month/대구월별확진자수.csv', sep=',')

In [49]:
df = pd.read_csv('confirmed-month/제주월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)

In [50]:
df

            지역  누적확진자  제주월별확진자
날짜
2020-02-01  제주      2        0
2020-03-01  제주      9        7
2020-04-01  제주     13        4
2020-05-01  제주     15        2
2020-06-01  제주     19        4
2020-07-01  제주     26        7
2020-08-01  제주     45       19
2020-09-01  제주     59       14
2020-10-01  제주     59        0
2020-11-01  제주     80       21
2020-12-01  제주    416      336
2021-01-01  제주    522      106
2021-02-01  제주    570       48
2021-03-01  제주    625       55
2021-04-01  제주    707       82
2021-05-01  제주   1030      323
2021-06-01  제주   1264      234

In [51]:
df=df.replace(0, df['누적확진자']['2020-02-01'])

In [52]:
df

            지역  누적확진자  제주월별확진자
날짜
2020-02-01  제주      2        2
2020-03-01  제주      9        7
2020-04-01  제주     13        4
2020-05-01  제주     15        2
2020-06-01  제주     19        4
2020-07-01  제주     26        7
2020-08-01  제주     45       19
2020-09-01  제주     59       14
2020-10-01  제주     59        2
2020-11-01  제주     80       21
2020-12-01  제주    416      336
2021-01-01  제주    522      106
2021-02-01  제주    570       48
2021-03-01  제주    625       55
2021-04-01  제주    707       82
2021-05-01  제주   1030      323
2021-06-01  제주   1264      234

In [53]:
df.to_csv('confirmed-month/제주월별확진자수.csv', sep=',')

In [59]:
df = pd.read_csv('confirmed-month/서울월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df=df.replace(0, df['누적확진자']['2020-01-02'])
df.to_csv('confirmed-month/서울월별확진자수.csv', sep=',')

In [58]:
df

            지역  누적확진자  서울월별확진자
날짜
2020-01-02  서울     77        0
2020-01-03  서울    450      373
2020-01-04  서울    633      183
2020-01-05  서울    861      228
2020-01-06  서울   1312      451
2020-01-07  서울   1600      288
2020-01-08  서울   3867     2267
2020-01-09  서울   5293     1426
2020-01-10  서울   6011      718
2020-01-11  서울   8812     2801
2020-01-12  서울  18996    10184
2021-01-01  서울  24156     5160
2021-01-02  서울  28236     4080
2021-01-03  서울  32030     3794
2021-01-04  서울  37837     5807
2021-01-05  서울  43196     5359
2021-01-06  서울  49987     6791

In [60]:
df = pd.read_csv('confirmed-month/부산월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df=df.replace(0, df['누적확진자']['2020-01-02'])
df.to_csv('confirmed-month/부산월별확진자수.csv', sep=',')

In [61]:
df = pd.read_csv('confirmed-month/광주월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df=df.replace(0, df['누적확진자']['2020-01-02'])
df.to_csv('confirmed-month/광주월별확진자수.csv', sep=',')

In [63]:
df = pd.read_csv('confirmed-month/인천월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df=df.replace(0, df['누적확진자']['2020-01-02'])
df.to_csv('confirmed-month/인천월별확진자수.csv', sep=',')

In [64]:
df = pd.read_csv('confirmed-month/울산월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df=df.replace(0, df['누적확진자']['2020-01-02'])
df.to_csv('confirmed-month/울산월별확진자수.csv', sep=',')

In [65]:
df = pd.read_csv('confirmed-month/대전월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df=df.replace(0, df['누적확진자']['2020-01-02'])
df.to_csv('confirmed-month/대전월별확진자수.csv', sep=',')

In [66]:
df = pd.read_csv('confirmed-month/세종월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df=df.replace(0, df['누적확진자']['2020-01-02'])
df.to_csv('confirmed-month/세종월별확진자수.csv', sep=',')

In [67]:
df = pd.read_csv('confirmed-month/경기월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df=df.replace(0, df['누적확진자']['2020-01-02'])
df.to_csv('confirmed-month/경기월별확진자수.csv', sep=',')

In [68]:
df = pd.read_csv('confirmed-month/강원월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df=df.replace(0, df['누적확진자']['2020-01-02'])
df.to_csv('confirmed-month/강원월별확진자수.csv', sep=',')

In [69]:
df = pd.read_csv('confirmed-month/충북월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df=df.replace(0, df['누적확진자']['2020-01-02'])
df.to_csv('confirmed-month/충북월별확진자수.csv', sep=',')

In [70]:
df = pd.read_csv('confirmed-month/충남월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df=df.replace(0, df['누적확진자']['2020-01-02'])
df.to_csv('confirmed-month/충남월별확진자수.csv', sep=',')

In [71]:
df = pd.read_csv('confirmed-month/경북월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df=df.replace(0, df['누적확진자']['2020-01-02'])
df.to_csv('confirmed-month/경남월별확진자수.csv', sep=',')

In [72]:
df = pd.read_csv('confirmed-month/전북월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df=df.replace(0, df['누적확진자']['2020-01-02'])
df.to_csv('confirmed-month/전북월별확진자수.csv', sep=',')

In [73]:
df = pd.read_csv('confirmed-month/경남월별확진자수.csv',encoding='UTF-8',index_col=0,parse_dates=['날짜'], dayfirst=True,infer_datetime_format=True)
df=df.replace(0, df['누적확진자']['2020-01-02'])
df.to_csv('confirmed-month/경남월별확진자수.csv', sep=',')

KeyError: '2020-01-02'