In [2]:
import pandas as pd

In [3]:
# 데이터 파일 읽어오기 2021년 1월
df = pd.read_csv('dust/202101dust.csv', encoding='UTF-8')

In [4]:
df.head()

,날짜,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,경북,경남,제주,세종,avg2.5
0,2021-01-01,16,14,15,16,17,19,11,19,12,24,27,19,11,15,11,10,31,16.882353
1,2021-01-02,11,19,20,11,20,17,17,12,12,23,21,21,15,19,15,14,23,17.058824
2,2021-01-03,14,13,15,14,20,17,12,16,12,21,21,19,16,16,13,20,21,16.470588
3,2021-01-04,22,25,26,22,32,22,21,24,16,28,32,29,24,25,22,23,32,25.000000
4,2021-01-05,15,28,25,13,28,18,24,15,14,23,23,25,21,25,23,18,21,21.117647

In [ ]:
df['날짜'] = pd.to_datetime(df['날짜'])

In [ ]:
df.info()

In [ ]:
df['avg2.5'] = (df['서울']+df['부산']+df['대구']+df['인천']+df['광주']+df['대전']+df['울산']+df['경기']
             +df['강원']+df['충북']+df['충남']+df['전북']+df['전남']+df['경북']+df['경남']+df['제주']+df['세종']) / 17

In [ ]:
df.head()

In [ ]:
df=df.sort_values(by='날짜', ascending=True)

In [ ]:
df.head()

In [ ]:
df=df.reset_index(drop=True)

In [ ]:
df.head()

In [ ]:
df.to_csv('dust/202101dust.csv', sep=',')

In [ ]:
df1 = df[['날짜','avg2.5']]

In [ ]:
df1.head()

In [ ]:
df1.to_csv('dust/202101dustavg2.5.csv', sep=',')

In [ ]:
# 데이터 파일 읽어오기 2021년 2월
df = pd.read_csv('dust/202102dust.csv', encoding='euc-kr')

In [ ]:
df.head()

In [ ]:
df['날짜'] = pd.to_datetime(df['날짜'])

In [ ]:
df['avg2.5'] = (df['서울']+df['부산']+df['대구']+df['인천']+df['광주']+df['대전']+df['울산']+df['경기']
             +df['강원']+df['충북']+df['충남']+df['전북']+df['전남']+df['경북']+df['경남']+df['제주']+df['세종']) / 17

In [ ]:
df=df.sort_values(by='날짜', ascending=True)

In [ ]:
df=df.reset_index(drop=True)

In [ ]:
df

In [ ]:
df.to_csv('dust/202102dust.csv', sep=',')

In [ ]:
df1 = df[['날짜','avg2.5']]

In [ ]:
df1.to_csv('dust/202102dustavg2.5.csv', sep=',')

In [ ]:
# 데이터 파일 읽어오기 2021년 3월
df = pd.read_csv('dust/202103dust.csv', encoding='euc-kr')

In [ ]:
df['날짜'] = pd.to_datetime(df['날짜'])

In [ ]:
df['avg2.5'] = (df['서울']+df['부산']+df['대구']+df['인천']+df['광주']+df['대전']+df['울산']+df['경기']
             +df['강원']+df['충북']+df['충남']+df['전북']+df['전남']+df['경북']+df['경남']+df['제주']+df['세종']) / 17

In [ ]:
df=df.sort_values(by='날짜', ascending=True)

In [ ]:
df=df.reset_index(drop=True)

In [ ]:
df

In [ ]:
df.to_csv('dust/202103dust.csv', sep=',') #3월 저장

In [ ]:
df1 = df[['날짜','avg2.5']]

In [ ]:
df1.to_csv('dust/202103dustavg2.5.csv', sep=',') #3월 날짜, avg2.5 저장

In [ ]:
df1

In [ ]:
# 데이터 파일 읽어오기 2021년 4월
df = pd.read_csv('dust/202104dust.csv', encoding='euc-kr')

In [ ]:
df['날짜'] = pd.to_datetime(df['날짜'])

In [ ]:
df['avg2.5'] = (df['서울']+df['부산']+df['대구']+df['인천']+df['광주']+df['대전']+df['울산']+df['경기']
             +df['강원']+df['충북']+df['충남']+df['전북']+df['전남']+df['경북']+df['경남']+df['제주']+df['세종']) / 17

In [ ]:
df=df.sort_values(by='날짜', ascending=True)

In [ ]:
df=df.reset_index(drop=True)

In [ ]:
df

In [ ]:
df.to_csv('dust/202104dust.csv', sep=',') #4월 저장

In [ ]:
df1 = df[['날짜','avg2.5']]

In [ ]:
df1.to_csv('dust/202104dustavg2.5.csv', sep=',') #4월 날짜, avg2.5 저장

In [ ]:
df1

In [ ]:
# 데이터 파일 읽어오기 2021년 5월
df = pd.read_csv('dust/202105dust.csv', encoding='euc-kr')

In [ ]:
df['날짜'] = pd.to_datetime(df['날짜'])

In [ ]:
df['avg2.5'] = (df['서울']+df['부산']+df['대구']+df['인천']+df['광주']+df['대전']+df['울산']+df['경기']
             +df['강원']+df['충북']+df['충남']+df['전북']+df['전남']+df['경북']+df['경남']+df['제주']+df['세종']) / 17

In [ ]:
df=df.sort_values(by='날짜', ascending=True)

In [ ]:
df=df.reset_index(drop=True)

In [ ]:
df

In [ ]:
df.to_csv('dust/202105dust.csv', sep=',') #5월 저장

In [ ]:
df1 = df[['날짜','avg2.5']]

In [ ]:
df1.to_csv('dust/202105dustavg2.5.csv', sep=',') #5월 날짜, avg2.5 저장

In [ ]:
df1

In [ ]:
# 데이터 파일 읽어오기 2021년 6월
df = pd.read_csv('dust/202106dust.csv', encoding='euc-kr')

In [ ]:
df['날짜'] = pd.to_datetime(df['날짜'])

In [ ]:
df['avg2.5'] = (df['서울']+df['부산']+df['대구']+df['인천']+df['광주']+df['대전']+df['울산']+df['경기']
             +df['강원']+df['충북']+df['충남']+df['전북']+df['전남']+df['경북']+df['경남']+df['제주']+df['세종']) / 17

In [ ]:
df=df.sort_values(by='날짜', ascending=True)

In [ ]:
df=df.reset_index(drop=True)

In [ ]:
df

In [ ]:
df.to_csv('dust/202106dust.csv', sep=',') #6월 저장

In [ ]:
df1 = df[['날짜','avg2.5']]

In [ ]:
df1.to_csv('dust/202106dustavg2.5.csv', sep=',') #6월 날짜, avg2.5 저장

In [ ]:
df1

In [6]:
# 데이터 파일 읽어오기 2021년 1월 pm10
df = pd.read_csv('dust/202101dust10pm.csv', encoding='UTF-8')

In [7]:
df

,Unnamed: 0,날짜,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,경북,경남,제주,세종,avg2.5
0,0,2021-01-01,25,20,22,26,23,31,19,30,22,33,36,28,18,24,19,17,42,25.588235
1,1,2021-01-02,32,32,39,29,32,39,32,36,30,42,41,40,27,38,29,23,43,34.352941
2,2,2021-01-03,35,27,35,35,38,42,29,42,32,45,46,39,35,37,28,42,47,37.294118
3,3,2021-01-04,37,41,45,39,46,44,37,42,30,45,48,44,40,42,38,38,51,41.588235
4,4,2021-01-05,26,42,39,24,36,35,39,30,25,37,36,36,31,39,35,29,36,33.823529
5,5,2021-01-06,24,19,21,26,18,24,20,29,20,27,28,20,15,23,17,22,29,22.470588
6,6,2021-01-07,31,26,25,25,18,25,23,30,29,24,24,17,18,26,18,14,29,23.647059
7,7,2021-01-08,19,17,16,20,17,20,14,20,16,22,24,21,14,17,14,10,25,18.000000
8,8,2021-01-09,24,17,18,24,19,21,14,26,20,26,29,25,16,18,15,12,31,20.882353
9,9,2021-01-10,31,19,21,29,27,27,17,32,25,34,35,28,21,22,19,18,37,26.000000
10,10,2021-01-11,44,33,39,49,32,43,28,51,31,47,49,40,26,31,28,20,54,37.941176
11,11,2021-01-12,58,34,45,53,43,44,29,61,43,56,56,43,34,38,34,41,61,45.470588
12,12,2021-01-13,101,96,89,99,77,82,94,102,99,85,101,93,77,93,81,89,81,90.529412
13,13,2021-01-14,75,76,75,64,79,97,68,83,82,105,88,89,81,78,73,56,113,81.294118
14,14,2021-01-15,74,54,64,66,66,72,52,79,81,80,77,67,58,63,50,40,80,66.058824
15,15,2021-01-16,51,75,85,47,58,74,77,55,74,74,63,60,61,89,71,59,74,67.470588
16,16,2021-01-17,19,19,17,17,18,17,17,20,20,19,20,17,16,19,14,17,19,17.941176
17,17,2021-01-18,35,47,42,35,46,37,44,39,31,36,45,40,46,39,39,63,37,41.235294
18,18,2021-01-19,30,28,27,30,27,27,24,33,29,30,31,24,24,26,23,20,33,27.411765
19,19,2021-01-20,44,31,45,43,35,37,29,49,47,46,42,31,26,37,30,17,49,37.529412
20,20,2021-01-21,46,35,62,50,34,48,41,55,42,60,49,34,28,46,33,23,65,44.176471
21,21,2021-01-22,37,35,59,32,26,30,38,39,27,47,47,33,29,42,37,19,52,37.000000
22,22,2021-01-23,11,23,20,15,25,24,24,13,10,21,28,32,26,24,25,20,26,21.588235
23,23,2021-01-24,12,22,16,14,17,13,21,14,15,17,18,16,17,18,17,24,19,17.058824
24,24,2021-01-25,23,17,24,32,25,19,16,29,23,24,29,23,20,20,19,22,25,22.941176
25,25,2021-01-26,36,16,22,41,22,21,15,38,25,26,33,29,16,19,15,13,29,24.470588
26,26,2021-01-27,37,28,35,34,38,44,26,43,33,46,45,40,30,33,25,30,45,36.000000
27,27,2021-01-28,31,39,41,32,41,38,33,36,34,38,40,38,38,37,34,48,38,37.411765
28,28,2021-01-29,22,29,33,21,25,31,25,25,20,26,30,27,27,28,26,29,29,26.647059
29,29,2021-01-30,47,71,67,54,63,62,66,56,39,54,77,81,58,60,62,51,56,60.235294
30,30,2021-01-31,51,58,54,52,65,51,44,58,42,54,64,67,63,43,58,33,57,53.764706

In [8]:
df.drop('avg2.5', axis=1, inplace=True)

In [9]:
df

,Unnamed: 0,날짜,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,경북,경남,제주,세종
0,0,2021-01-01,25,20,22,26,23,31,19,30,22,33,36,28,18,24,19,17,42
1,1,2021-01-02,32,32,39,29,32,39,32,36,30,42,41,40,27,38,29,23,43
2,2,2021-01-03,35,27,35,35,38,42,29,42,32,45,46,39,35,37,28,42,47
3,3,2021-01-04,37,41,45,39,46,44,37,42,30,45,48,44,40,42,38,38,51
4,4,2021-01-05,26,42,39,24,36,35,39,30,25,37,36,36,31,39,35,29,36
5,5,2021-01-06,24,19,21,26,18,24,20,29,20,27,28,20,15,23,17,22,29
6,6,2021-01-07,31,26,25,25,18,25,23,30,29,24,24,17,18,26,18,14,29
7,7,2021-01-08,19,17,16,20,17,20,14,20,16,22,24,21,14,17,14,10,25
8,8,2021-01-09,24,17,18,24,19,21,14,26,20,26,29,25,16,18,15,12,31
9,9,2021-01-10,31,19,21,29,27,27,17,32,25,34,35,28,21,22,19,18,37
10,10,2021-01-11,44,33,39,49,32,43,28,51,31,47,49,40,26,31,28,20,54
11,11,2021-01-12,58,34,45,53,43,44,29,61,43,56,56,43,34,38,34,41,61
12,12,2021-01-13,101,96,89,99,77,82,94,102,99,85,101,93,77,93,81,89,81
13,13,2021-01-14,75,76,75,64,79,97,68,83,82,105,88,89,81,78,73,56,113
14,14,2021-01-15,74,54,64,66,66,72,52,79,81,80,77,67,58,63,50,40,80
15,15,2021-01-16,51,75,85,47,58,74,77,55,74,74,63,60,61,89,71,59,74
16,16,2021-01-17,19,19,17,17,18,17,17,20,20,19,20,17,16,19,14,17,19
17,17,2021-01-18,35,47,42,35,46,37,44,39,31,36,45,40,46,39,39,63,37
18,18,2021-01-19,30,28,27,30,27,27,24,33,29,30,31,24,24,26,23,20,33
19,19,2021-01-20,44,31,45,43,35,37,29,49,47,46,42,31,26,37,30,17,49
20,20,2021-01-21,46,35,62,50,34,48,41,55,42,60,49,34,28,46,33,23,65
21,21,2021-01-22,37,35,59,32,26,30,38,39,27,47,47,33,29,42,37,19,52
22,22,2021-01-23,11,23,20,15,25,24,24,13,10,21,28,32,26,24,25,20,26
23,23,2021-01-24,12,22,16,14,17,13,21,14,15,17,18,16,17,18,17,24,19
24,24,2021-01-25,23,17,24,32,25,19,16,29,23,24,29,23,20,20,19,22,25
25,25,2021-01-26,36,16,22,41,22,21,15,38,25,26,33,29,16,19,15,13,29
26,26,2021-01-27,37,28,35,34,38,44,26,43,33,46,45,40,30,33,25,30,45
27,27,2021-01-28,31,39,41,32,41,38,33,36,34,38,40,38,38,37,34,48,38
28,28,2021-01-29,22,29,33,21,25,31,25,25,20,26,30,27,27,28,26,29,29
29,29,2021-01-30,47,71,67,54,63,62,66,56,39,54,77,81,58,60,62,51,56
30,30,2021-01-31,51,58,54,52,65,51,44,58,42,54,64,67,63,43,58,33,57

In [16]:
df['날짜'] = pd.to_datetime(df['날짜'])

In [17]:
df['avg10'] = (df['서울']+df['부산']+df['대구']+df['인천']+df['광주']+df['대전']+df['울산']+df['경기']
             +df['강원']+df['충북']+df['충남']+df['전북']+df['전남']+df['경북']+df['경남']+df['제주']+df['세종']) / 17

In [18]:
df=df.sort_values(by='날짜', ascending=True)

In [19]:
df=df.reset_index(drop=True)

In [20]:
df

,Unnamed: 0,날짜,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,경북,경남,제주,세종,avg10
0,0,2021-01-01,25,20,22,26,23,31,19,30,22,33,36,28,18,24,19,17,42,25.588235
1,1,2021-01-02,32,32,39,29,32,39,32,36,30,42,41,40,27,38,29,23,43,34.352941
2,2,2021-01-03,35,27,35,35,38,42,29,42,32,45,46,39,35,37,28,42,47,37.294118
3,3,2021-01-04,37,41,45,39,46,44,37,42,30,45,48,44,40,42,38,38,51,41.588235
4,4,2021-01-05,26,42,39,24,36,35,39,30,25,37,36,36,31,39,35,29,36,33.823529
5,5,2021-01-06,24,19,21,26,18,24,20,29,20,27,28,20,15,23,17,22,29,22.470588
6,6,2021-01-07,31,26,25,25,18,25,23,30,29,24,24,17,18,26,18,14,29,23.647059
7,7,2021-01-08,19,17,16,20,17,20,14,20,16,22,24,21,14,17,14,10,25,18.000000
8,8,2021-01-09,24,17,18,24,19,21,14,26,20,26,29,25,16,18,15,12,31,20.882353
9,9,2021-01-10,31,19,21,29,27,27,17,32,25,34,35,28,21,22,19,18,37,26.000000
10,10,2021-01-11,44,33,39,49,32,43,28,51,31,47,49,40,26,31,28,20,54,37.941176
11,11,2021-01-12,58,34,45,53,43,44,29,61,43,56,56,43,34,38,34,41,61,45.470588
12,12,2021-01-13,101,96,89,99,77,82,94,102,99,85,101,93,77,93,81,89,81,90.529412
13,13,2021-01-14,75,76,75,64,79,97,68,83,82,105,88,89,81,78,73,56,113,81.294118
14,14,2021-01-15,74,54,64,66,66,72,52,79,81,80,77,67,58,63,50,40,80,66.058824
15,15,2021-01-16,51,75,85,47,58,74,77,55,74,74,63,60,61,89,71,59,74,67.470588
16,16,2021-01-17,19,19,17,17,18,17,17,20,20,19,20,17,16,19,14,17,19,17.941176
17,17,2021-01-18,35,47,42,35,46,37,44,39,31,36,45,40,46,39,39,63,37,41.235294
18,18,2021-01-19,30,28,27,30,27,27,24,33,29,30,31,24,24,26,23,20,33,27.411765
19,19,2021-01-20,44,31,45,43,35,37,29,49,47,46,42,31,26,37,30,17,49,37.529412
20,20,2021-01-21,46,35,62,50,34,48,41,55,42,60,49,34,28,46,33,23,65,44.176471
21,21,2021-01-22,37,35,59,32,26,30,38,39,27,47,47,33,29,42,37,19,52,37.000000
22,22,2021-01-23,11,23,20,15,25,24,24,13,10,21,28,32,26,24,25,20,26,21.588235
23,23,2021-01-24,12,22,16,14,17,13,21,14,15,17,18,16,17,18,17,24,19,17.058824
24,24,2021-01-25,23,17,24,32,25,19,16,29,23,24,29,23,20,20,19,22,25,22.941176
25,25,2021-01-26,36,16,22,41,22,21,15,38,25,26,33,29,16,19,15,13,29,24.470588
26,26,2021-01-27,37,28,35,34,38,44,26,43,33,46,45,40,30,33,25,30,45,36.000000
27,27,2021-01-28,31,39,41,32,41,38,33,36,34,38,40,38,38,37,34,48,38,37.411765
28,28,2021-01-29,22,29,33,21,25,31,25,25,20,26,30,27,27,28,26,29,29,26.647059
29,29,2021-01-30,47,71,67,54,63,62,66,56,39,54,77,81,58,60,62,51,56,60.235294
30,30,2021-01-31,51,58,54,52,65,51,44,58,42,54,64,67,63,43,58,33,57,53.764706

In [23]:
df.to_csv('dust/202101dust10pm.csv', sep=',') #1월 10pm저장

In [24]:
df1 = df[['날짜','avg10']]

In [25]:
df1.to_csv('dust/202101dustavg10.csv', sep=',') #1월 날짜, avg10 저장

In [26]:
df1

           날짜      avg10
0  2021-01-01  25.588235
1  2021-01-02  34.352941
2  2021-01-03  37.294118
3  2021-01-04  41.588235
4  2021-01-05  33.823529
5  2021-01-06  22.470588
6  2021-01-07  23.647059
7  2021-01-08  18.000000
8  2021-01-09  20.882353
9  2021-01-10  26.000000
10 2021-01-11  37.941176
11 2021-01-12  45.470588
12 2021-01-13  90.529412
13 2021-01-14  81.294118
14 2021-01-15  66.058824
15 2021-01-16  67.470588
16 2021-01-17  17.941176
17 2021-01-18  41.235294
18 2021-01-19  27.411765
19 2021-01-20  37.529412
20 2021-01-21  44.176471
21 2021-01-22  37.000000
22 2021-01-23  21.588235
23 2021-01-24  17.058824
24 2021-01-25  22.941176
25 2021-01-26  24.470588
26 2021-01-27  36.000000
27 2021-01-28  37.411765
28 2021-01-29  26.647059
29 2021-01-30  60.235294
30 2021-01-31  53.764706

In [27]:
df

,Unnamed: 0,날짜,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,경북,경남,제주,세종,avg10
0,0,2021-01-01,25,20,22,26,23,31,19,30,22,33,36,28,18,24,19,17,42,25.588235
1,1,2021-01-02,32,32,39,29,32,39,32,36,30,42,41,40,27,38,29,23,43,34.352941
2,2,2021-01-03,35,27,35,35,38,42,29,42,32,45,46,39,35,37,28,42,47,37.294118
3,3,2021-01-04,37,41,45,39,46,44,37,42,30,45,48,44,40,42,38,38,51,41.588235
4,4,2021-01-05,26,42,39,24,36,35,39,30,25,37,36,36,31,39,35,29,36,33.823529
5,5,2021-01-06,24,19,21,26,18,24,20,29,20,27,28,20,15,23,17,22,29,22.470588
6,6,2021-01-07,31,26,25,25,18,25,23,30,29,24,24,17,18,26,18,14,29,23.647059
7,7,2021-01-08,19,17,16,20,17,20,14,20,16,22,24,21,14,17,14,10,25,18.000000
8,8,2021-01-09,24,17,18,24,19,21,14,26,20,26,29,25,16,18,15,12,31,20.882353
9,9,2021-01-10,31,19,21,29,27,27,17,32,25,34,35,28,21,22,19,18,37,26.000000
10,10,2021-01-11,44,33,39,49,32,43,28,51,31,47,49,40,26,31,28,20,54,37.941176
11,11,2021-01-12,58,34,45,53,43,44,29,61,43,56,56,43,34,38,34,41,61,45.470588
12,12,2021-01-13,101,96,89,99,77,82,94,102,99,85,101,93,77,93,81,89,81,90.529412
13,13,2021-01-14,75,76,75,64,79,97,68,83,82,105,88,89,81,78,73,56,113,81.294118
14,14,2021-01-15,74,54,64,66,66,72,52,79,81,80,77,67,58,63,50,40,80,66.058824
15,15,2021-01-16,51,75,85,47,58,74,77,55,74,74,63,60,61,89,71,59,74,67.470588
16,16,2021-01-17,19,19,17,17,18,17,17,20,20,19,20,17,16,19,14,17,19,17.941176
17,17,2021-01-18,35,47,42,35,46,37,44,39,31,36,45,40,46,39,39,63,37,41.235294
18,18,2021-01-19,30,28,27,30,27,27,24,33,29,30,31,24,24,26,23,20,33,27.411765
19,19,2021-01-20,44,31,45,43,35,37,29,49,47,46,42,31,26,37,30,17,49,37.529412
20,20,2021-01-21,46,35,62,50,34,48,41,55,42,60,49,34,28,46,33,23,65,44.176471
21,21,2021-01-22,37,35,59,32,26,30,38,39,27,47,47,33,29,42,37,19,52,37.000000
22,22,2021-01-23,11,23,20,15,25,24,24,13,10,21,28,32,26,24,25,20,26,21.588235
23,23,2021-01-24,12,22,16,14,17,13,21,14,15,17,18,16,17,18,17,24,19,17.058824
24,24,2021-01-25,23,17,24,32,25,19,16,29,23,24,29,23,20,20,19,22,25,22.941176
25,25,2021-01-26,36,16,22,41,22,21,15,38,25,26,33,29,16,19,15,13,29,24.470588
26,26,2021-01-27,37,28,35,34,38,44,26,43,33,46,45,40,30,33,25,30,45,36.000000
27,27,2021-01-28,31,39,41,32,41,38,33,36,34,38,40,38,38,37,34,48,38,37.411765
28,28,2021-01-29,22,29,33,21,25,31,25,25,20,26,30,27,27,28,26,29,29,26.647059
29,29,2021-01-30,47,71,67,54,63,62,66,56,39,54,77,81,58,60,62,51,56,60.235294
30,30,2021-01-31,51,58,54,52,65,51,44,58,42,54,64,67,63,43,58,33,57,53.764706

In [28]:
# 데이터 파일 읽어오기 2021년 1월 pm10
df = pd.read_csv('dust/202101dust.csv', encoding='UTF-8')

In [29]:
df

,날짜,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,경북,경남,제주,세종,avg2.5
0,2021-01-01,16,14,15,16,17,19,11,19,12,24,27,19,11,15,11,10,31,16.882353
1,2021-01-02,11,19,20,11,20,17,17,12,12,23,21,21,15,19,15,14,23,17.058824
2,2021-01-03,14,13,15,14,20,17,12,16,12,21,21,19,16,16,13,20,21,16.470588
3,2021-01-04,22,25,26,22,32,22,21,24,16,28,32,29,24,25,22,23,32,25.000000
4,2021-01-05,15,28,25,13,28,18,24,15,14,23,23,25,21,25,23,18,21,21.117647
5,2021-01-06,13,11,12,13,12,12,10,13,9,17,17,12,9,13,10,14,17,12.588235
6,2021-01-07,11,12,10,10,11,8,9,10,9,11,11,7,8,11,8,8,9,9.588235
7,2021-01-08,10,11,9,10,14,10,7,10,7,14,15,15,10,9,9,6,14,10.588235
8,2021-01-09,15,11,10,14,16,12,7,15,11,17,19,19,11,11,10,7,18,13.117647
9,2021-01-10,22,13,14,19,22,16,10,21,16,24,24,22,14,14,12,10,24,17.470588
10,2021-01-11,32,22,26,33,27,29,18,36,21,35,37,31,18,21,19,14,42,27.117647
11,2021-01-12,47,23,32,37,35,30,19,48,31,42,43,33,22,27,22,20,49,32.941176
12,2021-01-13,45,33,38,34,40,27,34,43,40,41,36,31,27,37,29,22,42,35.235294
13,2021-01-14,29,29,37,25,40,29,28,31,28,41,34,38,32,31,28,19,42,31.823529
14,2021-01-15,34,21,31,29,36,27,22,35,31,39,36,31,25,27,22,15,39,29.411765
15,2021-01-16,35,33,37,31,26,28,33,34,34,36,29,26,24,37,29,22,29,30.764706
16,2021-01-17,13,10,9,11,12,8,8,12,11,12,12,9,9,11,8,9,9,10.176471
17,2021-01-18,17,25,22,16,25,17,24,19,17,21,24,21,20,21,20,25,21,20.882353
18,2021-01-19,15,15,13,15,14,11,11,16,13,16,17,12,12,13,11,8,15,13.352941
19,2021-01-20,25,18,27,24,20,20,16,28,23,28,28,20,15,21,17,8,32,21.764706
20,2021-01-21,30,22,41,32,24,31,28,37,26,40,37,25,18,30,21,12,48,29.529412
21,2021-01-22,31,27,47,24,22,22,30,31,20,38,38,28,21,32,29,13,41,29.058824
22,2021-01-23,8,13,13,11,20,14,13,8,6,15,20,25,17,15,17,11,17,14.294118
23,2021-01-24,9,11,9,10,11,6,11,9,9,10,12,10,10,10,10,11,11,9.941176
24,2021-01-25,16,8,14,22,15,9,8,18,13,14,18,15,11,11,11,7,15,13.235294
25,2021-01-26,28,10,15,30,18,12,9,28,17,18,26,23,10,12,10,7,20,17.235294
26,2021-01-27,18,17,20,15,18,19,16,20,16,26,22,20,14,19,14,16,21,18.294118
27,2021-01-28,16,18,19,16,21,14,15,16,15,18,19,18,16,17,17,18,17,17.058824
28,2021-01-29,9,11,9,10,13,9,8,9,7,9,12,10,10,9,9,10,9,9.588235
29,2021-01-30,23,24,25,24,27,20,22,25,20,24,33,32,18,22,22,14,23,23.411765
30,2021-01-31,27,28,25,24,32,20,20,29,21,27,31,31,24,19,25,11,28,24.823529

In [31]:
# 데이터 파일 읽어오기 2021년 2월 pm10
df = pd.read_csv('dust/202102dust10pm.csv', encoding='euc-kr')

In [32]:
df['날짜'] = pd.to_datetime(df['날짜'])

In [33]:
df['avg10'] = (df['서울']+df['부산']+df['대구']+df['인천']+df['광주']+df['대전']+df['울산']+df['경기']
             +df['강원']+df['충북']+df['충남']+df['전북']+df['전남']+df['경북']+df['경남']+df['제주']+df['세종']) / 17

In [34]:
df=df.sort_values(by='날짜', ascending=True)

In [35]:
df=df.reset_index(drop=True)

In [36]:
df

,날짜,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,경북,경남,제주,세종,avg10
0,2021-02-01,66,45,62,58,78,77,43,71,60,76,80,84,63,55,47,44,82,64.176471
1,2021-02-02,31,48,34,27,36,33,39,32,29,35,34,31,30,37,34,45,36,34.764706
2,2021-02-03,31,26,28,31,30,33,25,34,28,32,31,27,25,27,22,40,33,29.588235
3,2021-02-04,23,34,28,21,35,31,26,24,20,27,30,31,29,27,28,48,29,28.882353
4,2021-02-05,26,26,40,26,34,30,23,30,32,33,28,27,24,31,24,18,32,28.470588
5,2021-02-06,63,44,62,56,49,50,44,66,62,60,61,45,37,56,41,21,58,51.470588
6,2021-02-07,79,73,76,60,82,76,76,81,69,80,84,85,75,77,65,102,76,77.411765
7,2021-02-08,25,25,22,23,26,26,22,27,23,26,27,25,21,23,18,25,27,24.176471
8,2021-02-09,22,22,23,22,23,26,18,27,25,27,28,24,18,23,18,19,31,23.294118
9,2021-02-10,34,45,45,30,31,34,46,37,40,40,36,32,25,42,36,19,42,36.117647
10,2021-02-11,68,54,54,65,47,48,51,69,55,66,63,50,44,54,47,39,60,54.941176
11,2021-02-12,84,48,53,98,57,57,47,90,49,63,91,62,53,50,44,41,69,62.117647
12,2021-02-13,90,45,46,84,54,65,49,95,50,70,97,67,52,49,39,45,81,63.411765
13,2021-02-14,89,41,64,94,50,53,54,93,47,60,95,64,53,54,45,29,76,62.411765
14,2021-02-15,51,28,37,39,32,35,26,49,34,41,47,38,27,32,26,28,37,35.705882
15,2021-02-16,22,22,21,20,22,21,20,22,18,21,23,19,19,20,18,25,22,20.882353
16,2021-02-17,39,23,23,32,16,27,19,39,34,31,33,21,19,25,17,19,29,26.235294
17,2021-02-18,40,27,32,41,25,36,27,44,34,37,37,28,24,33,24,22,34,32.058824
18,2021-02-19,43,34,35,39,31,36,31,46,48,42,39,34,27,36,29,26,38,36.117647
19,2021-02-20,66,59,67,65,64,78,59,69,60,67,83,73,57,67,54,52,76,65.647059
20,2021-02-21,70,56,58,65,52,62,55,72,55,62,64,55,47,58,48,35,61,57.352941
21,2021-02-22,53,44,49,51,51,49,42,59,51,56,53,50,43,48,40,47,48,49.058824
22,2021-02-23,50,26,25,51,36,42,26,56,37,47,49,40,28,31,21,26,43,37.294118
23,2021-02-24,49,32,38,49,52,45,30,59,34,52,61,49,35,38,28,32,50,43.117647
24,2021-02-25,55,33,46,61,38,44,28,66,37,55,78,59,30,38,34,28,64,46.705882
25,2021-02-26,35,21,32,37,20,31,21,39,27,39,51,27,20,28,22,22,43,30.294118
26,2021-02-27,16,24,23,20,20,18,21,20,17,20,25,20,21,22,20,33,21,21.235294
27,2021-02-28,22,24,24,26,21,19,23,28,21,24,30,22,20,24,21,28,24,23.588235

In [37]:
df.to_csv('dust/202102dust10pm.csv', sep=',') #2월 10pm저장

In [38]:
df1 = df[['날짜','avg10']]

In [39]:
df1.to_csv('dust/202102dustavg10.csv', sep=',') #2월 날짜, avg10 저장

In [40]:
# 데이터 파일 읽어오기 2021년 3월 pm10
df = pd.read_csv('dust/202103dust10pm.csv', encoding='euc-kr')

In [41]:
df['날짜'] = pd.to_datetime(df['날짜'])

In [42]:
df['avg10'] = (df['서울']+df['부산']+df['대구']+df['인천']+df['광주']+df['대전']+df['울산']+df['경기']
             +df['강원']+df['충북']+df['충남']+df['전북']+df['전남']+df['경북']+df['경남']+df['제주']+df['세종']) / 17

In [43]:
df=df.sort_values(by='날짜', ascending=True)

In [44]:
df=df.reset_index(drop=True)

In [45]:
df

,날짜,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,경북,경남,제주,세종,avg10
0,2021-03-01,15,26,26,18,11,13,22,17,12,19,19,12,14,23,18,18,16,17.588235
1,2021-03-02,10,13,11,11,16,12,12,12,10,11,16,14,11,12,9,19,15,12.588235
2,2021-03-03,37,25,32,39,29,29,24,41,25,30,39,29,21,25,22,20,32,29.352941
3,2021-03-04,42,32,43,41,26,33,31,46,32,37,38,30,20,32,28,18,38,33.352941
4,2021-03-05,36,28,36,38,23,38,31,41,30,43,43,35,20,31,25,21,41,32.941176
5,2021-03-06,28,32,35,30,50,32,31,31,21,33,43,50,37,31,31,42,37,34.941176
6,2021-03-07,22,20,21,21,36,30,15,26,17,26,36,40,30,20,21,38,32,26.529412
7,2021-03-08,41,26,36,41,46,59,21,49,32,55,59,54,39,31,29,44,62,42.588235
8,2021-03-09,46,29,40,41,41,56,29,54,42,55,58,51,31,35,30,32,59,42.882353
9,2021-03-10,91,52,57,79,65,56,49,84,57,60,81,70,55,55,50,60,64,63.823529
10,2021-03-11,118,39,51,106,65,63,36,116,57,67,102,82,46,44,37,37,81,67.470588
11,2021-03-12,69,17,25,83,22,43,20,82,44,51,77,37,18,30,15,24,55,41.882353
12,2021-03-13,53,49,42,52,25,36,50,52,50,40,44,34,24,42,31,34,37,40.882353
13,2021-03-14,77,49,52,69,46,52,51,73,60,63,69,58,42,52,39,49,64,56.764706
14,2021-03-15,82,52,55,72,55,54,54,78,59,59,67,53,45,53,42,40,63,57.823529
15,2021-03-16,93,54,60,100,70,71,49,104,75,85,98,79,64,73,57,60,77,74.647059
16,2021-03-17,94,87,89,89,78,90,89,103,81,88,99,86,71,91,65,66,94,85.882353
17,2021-03-18,97,69,73,93,70,86,65,103,70,83,89,73,66,71,63,65,96,78.352941
18,2021-03-19,69,37,41,76,60,43,36,73,55,43,70,65,47,41,37,43,46,51.882353
19,2021-03-20,28,19,20,40,24,23,17,35,28,26,45,36,21,22,17,16,30,26.294118
20,2021-03-21,42,32,36,42,49,44,32,46,34,49,55,51,41,38,30,49,47,42.176471
21,2021-03-22,37,32,33,37,43,43,29,41,32,38,49,46,37,34,30,37,40,37.529412
22,2021-03-23,77,82,85,72,81,92,79,87,84,88,89,86,73,92,71,73,85,82.117647
23,2021-03-24,60,65,61,53,54,53,56,65,62,59,58,56,51,62,51,44,54,56.705882
24,2021-03-25,65,47,57,41,48,51,38,65,56,65,53,49,40,50,45,41,53,50.823529
25,2021-03-26,104,62,61,106,64,68,60,104,64,80,83,69,59,62,50,62,73,72.411765
26,2021-03-27,58,48,48,63,31,43,51,62,43,47,52,39,32,50,38,29,47,45.941176
27,2021-03-28,19,19,15,16,27,14,16,18,19,16,20,21,25,15,17,61,15,20.764706
28,2021-03-29,288,478,367,363,507,400,410,332,222,315,505,564,519,360,452,578,371,413.588235
29,2021-03-30,126,166,96,134,188,168,132,148,76,149,236,290,240,106,119,421,189,175.529412
30,2021-03-31,41,74,66,54,71,46,72,52,37,47,56,56,79,61,71,91,49,60.176471

In [46]:
df.to_csv('dust/202103dust10pm.csv', sep=',') #3월 10pm저장

In [47]:
df1 = df[['날짜','avg10']]

In [48]:
df1.to_csv('dust/202103dustavg10.csv', sep=',') #3월 날짜, avg10 저장

In [49]:
df1

           날짜       avg10
0  2021-03-01   17.588235
1  2021-03-02   12.588235
2  2021-03-03   29.352941
3  2021-03-04   33.352941
4  2021-03-05   32.941176
5  2021-03-06   34.941176
6  2021-03-07   26.529412
7  2021-03-08   42.588235
8  2021-03-09   42.882353
9  2021-03-10   63.823529
10 2021-03-11   67.470588
11 2021-03-12   41.882353
12 2021-03-13   40.882353
13 2021-03-14   56.764706
14 2021-03-15   57.823529
15 2021-03-16   74.647059
16 2021-03-17   85.882353
17 2021-03-18   78.352941
18 2021-03-19   51.882353
19 2021-03-20   26.294118
20 2021-03-21   42.176471
21 2021-03-22   37.529412
22 2021-03-23   82.117647
23 2021-03-24   56.705882
24 2021-03-25   50.823529
25 2021-03-26   72.411765
26 2021-03-27   45.941176
27 2021-03-28   20.764706
28 2021-03-29  413.588235
29 2021-03-30  175.529412
30 2021-03-31   60.176471

In [50]:
# 데이터 파일 읽어오기 2021년 4월 pm10
df = pd.read_csv('dust/202104dust10pm.csv', encoding='euc-kr')

In [51]:
df['날짜'] = pd.to_datetime(df['날짜'])

In [52]:
df['avg10'] = (df['서울']+df['부산']+df['대구']+df['인천']+df['광주']+df['대전']+df['울산']+df['경기']
             +df['강원']+df['충북']+df['충남']+df['전북']+df['전남']+df['경북']+df['경남']+df['제주']+df['세종']) / 17

In [53]:
df=df.sort_values(by='날짜', ascending=True)

In [54]:
df=df.reset_index(drop=True)

In [55]:
df.to_csv('dust/202104dust10pm.csv', sep=',') #4월 10pm저장

In [56]:
df1 = df[['날짜','avg10']]

In [57]:
df1.to_csv('dust/202104dustavg10.csv', sep=',') #4월 날짜, avg10 저장

In [58]:
df1

           날짜      avg10
0  2021-04-01  56.764706
1  2021-04-02  48.705882
2  2021-04-03  32.823529
3  2021-04-04  11.529412
4  2021-04-05  20.117647
5  2021-04-06  34.411765
6  2021-04-07  47.411765
7  2021-04-08  36.705882
8  2021-04-09  30.411765
9  2021-04-10  27.588235
10 2021-04-11  32.470588
11 2021-04-12  26.941176
12 2021-04-13  16.411765
13 2021-04-14  26.294118
14 2021-04-15  35.411765
15 2021-04-16  47.176471
16 2021-04-17  86.941176
17 2021-04-18  31.352941
18 2021-04-19  42.764706
19 2021-04-20  56.529412
20 2021-04-21  63.529412
21 2021-04-22  60.000000
22 2021-04-23  37.235294
23 2021-04-24  27.470588
24 2021-04-25  29.529412
25 2021-04-26  24.647059
26 2021-04-27  30.529412
27 2021-04-28  62.941176
28 2021-04-29  72.882353
29 2021-04-30  45.000000

In [59]:
# 데이터 파일 읽어오기 2021년 5월 pm10
df = pd.read_csv('dust/202105dust10pm.csv', encoding='euc-kr')

In [60]:
df['날짜'] = pd.to_datetime(df['날짜'])

In [61]:
df['avg10'] = (df['서울']+df['부산']+df['대구']+df['인천']+df['광주']+df['대전']+df['울산']+df['경기']
             +df['강원']+df['충북']+df['충남']+df['전북']+df['전남']+df['경북']+df['경남']+df['제주']+df['세종']) / 17

In [62]:
df=df.sort_values(by='날짜', ascending=True)

In [63]:
df=df.reset_index(drop=True)

In [64]:
df.to_csv('dust/202105dust10pm.csv', sep=',') #5월 10pm저장

In [65]:
df1 = df[['날짜','avg10']]

In [66]:
df1.to_csv('dust/202105dustavg10.csv', sep=',') #5월 날짜, avg10 저장

In [67]:
df1

           날짜       avg10
0  2021-05-01   27.058824
1  2021-05-02   19.235294
2  2021-05-03   24.294118
3  2021-05-04   25.529412
4  2021-05-05   41.882353
5  2021-05-06   63.941176
6  2021-05-07  207.764706
7  2021-05-08  333.705882
8  2021-05-09   82.235294
9  2021-05-10   24.411765
10 2021-05-11   22.529412
11 2021-05-12   25.000000
12 2021-05-13   34.882353
13 2021-05-14   40.058824
14 2021-05-15   27.823529
15 2021-05-16   10.176471
16 2021-05-17   12.823529
17 2021-05-18   23.235294
18 2021-05-19   34.176471
19 2021-05-20   24.882353
20 2021-05-21   15.294118
21 2021-05-22   23.529412
22 2021-05-23   33.235294
23 2021-05-24   71.764706
24 2021-05-25   92.823529
25 2021-05-26   40.470588
26 2021-05-27   32.294118
27 2021-05-28   36.823529
28 2021-05-29   25.823529
29 2021-05-30   29.411765
30 2021-05-31   32.882353

In [68]:
# 데이터 파일 읽어오기 2021년 6월 pm10
df = pd.read_csv('dust/202106dust10pm.csv', encoding='euc-kr')

In [69]:
df['날짜'] = pd.to_datetime(df['날짜'])

In [70]:
df['avg10'] = (df['서울']+df['부산']+df['대구']+df['인천']+df['광주']+df['대전']+df['울산']+df['경기']
             +df['강원']+df['충북']+df['충남']+df['전북']+df['전남']+df['경북']+df['경남']+df['제주']+df['세종']) / 17

In [71]:
df=df.sort_values(by='날짜', ascending=True)

In [72]:
df=df.reset_index(drop=True)

In [73]:
df.to_csv('dust/202106dust10pm.csv', sep=',') #6월 10pm저장

In [74]:
df1 = df[['날짜','avg10']]

In [75]:
df1.to_csv('dust/202105dustavg10.csv', sep=',') #6월 날짜, avg10 저장

In [76]:
df1

           날짜      avg10
0  2021-06-01  37.941176
1  2021-06-02  46.176471
2  2021-06-03  26.000000
3  2021-06-04  22.294118
4  2021-06-05  48.117647
5  2021-06-06  50.000000
6  2021-06-07  39.647059
7  2021-06-08  37.470588
8  2021-06-09  40.176471
9  2021-06-10  43.117647
10 2021-06-11  18.941176
11 2021-06-12  23.588235
12 2021-06-13  27.705882
13 2021-06-14  31.058824
14 2021-06-15  21.529412
15 2021-06-16  11.588235
16 2021-06-17  16.000000
17 2021-06-18  17.764706
18 2021-06-19  33.294118
19 2021-06-20  41.117647
20 2021-06-21  38.294118
21 2021-06-22  27.235294
22 2021-06-23  23.941176
23 2021-06-24  26.882353
24 2021-06-25  30.823529
25 2021-06-26  23.588235
26 2021-06-27  25.647059
27 2021-06-28  28.000000
28 2021-06-29  28.823529
29 2021-06-30  31.470588

In [92]:
# 데이터 파일 읽어오기 2021년 6월 pm10
df = pd.read_csv('dust/202106dust10pm.csv', encoding='utf-8')

In [93]:
df

,날짜,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,경북,경남,제주,세종,avg10
0,2021-06-01,38,31,49,35,45,40,29,42,34,39,37,42,40,36,36,35,37,37.941176
1,2021-06-02,50,44,60,51,40,46,49,52,38,45,46,47,41,52,44,33,47,46.176471
2,2021-06-03,31,25,30,34,15,26,31,35,29,29,28,19,15,33,24,11,27,26.000000
3,2021-06-04,26,20,20,25,19,25,21,30,22,24,27,24,17,22,18,15,24,22.294118
4,2021-06-05,45,40,47,57,50,60,43,53,37,50,58,62,42,42,40,41,51,48.117647
5,2021-06-06,61,42,56,60,47,51,52,63,45,58,47,55,38,56,42,32,45,50.000000
6,2021-06-07,37,35,54,39,43,41,50,44,39,42,35,46,29,48,33,21,38,39.647059
7,2021-06-08,40,32,48,41,28,46,39,44,29,44,31,48,25,44,32,21,45,37.470588
8,2021-06-09,41,33,49,55,32,41,38,49,30,42,47,48,33,42,34,23,46,40.176471
9,2021-06-10,53,42,48,60,33,42,45,58,37,40,45,47,33,44,37,27,42,43.117647
10,2021-06-11,19,19,21,15,14,22,22,22,22,23,17,16,16,24,17,10,23,18.941176
11,2021-06-12,21,7,24,24,31,29,13,26,19,32,34,35,23,22,14,15,32,23.588235
12,2021-06-13,30,18,31,21,30,40,23,31,16,36,31,37,25,24,20,20,38,27.705882
13,2021-06-14,39,19,34,28,31,41,19,38,16,35,39,45,27,24,24,30,39,31.058824
14,2021-06-15,26,12,21,29,20,22,13,30,12,21,30,35,17,18,19,18,23,21.529412
15,2021-06-16,10,10,11,13,10,9,10,13,10,11,16,13,11,14,10,15,11,11.588235
16,2021-06-17,17,15,20,18,17,13,12,19,15,14,15,17,14,19,15,19,13,16.000000
17,2021-06-18,17,23,31,15,13,12,27,19,15,13,13,14,15,22,24,17,12,17.764706
18,2021-06-19,42,39,31,44,28,28,33,47,26,38,37,33,27,28,31,25,29,33.294118
19,2021-06-20,51,42,36,62,35,34,43,57,35,39,46,40,34,35,36,36,38,41.117647
20,2021-06-21,41,37,31,42,32,40,33,47,32,46,48,50,34,33,32,36,37,38.294118
21,2021-06-22,23,21,32,37,30,24,18,32,14,24,33,36,30,24,28,31,26,27.235294
22,2021-06-23,18,18,27,27,29,27,14,23,13,21,30,39,25,19,25,28,24,23.941176
23,2021-06-24,31,17,28,39,24,27,17,36,18,28,35,35,21,21,22,31,27,26.882353
24,2021-06-25,38,24,39,46,24,27,27,43,26,34,32,32,25,30,28,22,27,30.823529
25,2021-06-26,21,22,36,27,21,18,25,24,21,19,24,22,23,29,25,26,18,23.588235
26,2021-06-27,19,24,33,23,25,22,25,24,21,24,30,29,26,28,26,32,25,25.647059
27,2021-06-28,24,28,30,28,29,23,25,28,21,24,36,37,30,29,29,28,27,28.000000
28,2021-06-29,30,23,27,40,31,24,23,36,21,25,38,37,28,27,27,25,28,28.823529
29,2021-06-30,36,23,35,42,29,31,22,43,24,32,40,34,26,29,28,24,37,31.470588