In [2]:
import pandas as pd

In [2]:
# 데이터 파일 읽어오기 5월
DUST = pd.read_csv('data/2020년 5월.csv', encoding='euc-kr')

In [3]:
DUST.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384648 entries, 0 to 384647
Data columns (total 12 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   지역      384648 non-null  object
 1   망       384648 non-null  object
 2   측정소코드   384648 non-null  int64
 3   측정소명    384648 non-null  object
 4   측정일시    384648 non-null  int64
 5   SO2     367073 non-null  float64
 6   CO      366810 non-null  float64
 7   O3      370433 non-null  float64
 8   NO2     367863 non-null  float64
 9   PM10    366775 non-null  float64
 10  PM25    361196 non-null  float64
 11  주소      384648 non-null  object
dtypes: float64(6), int64(2), object(4)
memory usage: 35.2+ MB

In [4]:
DUST.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 중구,도시대기,111121,중구,2020050101,0.003,0.3,0.038,0.008,34.0,25.0,서울 중구 덕수궁길 15
1,서울 중구,도시대기,111121,중구,2020050102,0.002,0.3,0.038,0.007,37.0,26.0,서울 중구 덕수궁길 15
2,서울 중구,도시대기,111121,중구,2020050103,0.003,0.4,0.036,0.009,38.0,29.0,서울 중구 덕수궁길 15
3,서울 중구,도시대기,111121,중구,2020050104,0.002,0.4,0.037,0.008,43.0,31.0,서울 중구 덕수궁길 15
4,서울 중구,도시대기,111121,중구,2020050105,0.003,0.4,0.038,0.008,43.0,33.0,서울 중구 덕수궁길 15

In [5]:
DUST_EX=DUST[['지역','망','측정소명','측정일시','PM10','PM25','주소']] # df=df1[['지역', '망','측정소명','측정일시','PM10','PM25','주소']]

In [6]:
DUST_EX.head()

      지역     망 측정소명        측정일시  PM10  PM25             주소
0  서울 중구  도시대기   중구  2020050101  34.0  25.0  서울 중구 덕수궁길 15
1  서울 중구  도시대기   중구  2020050102  37.0  26.0  서울 중구 덕수궁길 15
2  서울 중구  도시대기   중구  2020050103  38.0  29.0  서울 중구 덕수궁길 15
3  서울 중구  도시대기   중구  2020050104  43.0  31.0  서울 중구 덕수궁길 15
4  서울 중구  도시대기   중구  2020050105  43.0  33.0  서울 중구 덕수궁길 15

In [7]:
DUST_EX_2=DUST_EX[DUST_EX['망']=='도시대기'] #도시대기만 뽑아오기

In [8]:
DUST_EX_2.head()

      지역     망 측정소명        측정일시  PM10  PM25             주소
0  서울 중구  도시대기   중구  2020050101  34.0  25.0  서울 중구 덕수궁길 15
1  서울 중구  도시대기   중구  2020050102  37.0  26.0  서울 중구 덕수궁길 15
2  서울 중구  도시대기   중구  2020050103  38.0  29.0  서울 중구 덕수궁길 15
3  서울 중구  도시대기   중구  2020050104  43.0  31.0  서울 중구 덕수궁길 15
4  서울 중구  도시대기   중구  2020050105  43.0  33.0  서울 중구 덕수궁길 15

In [9]:
DUST = DUST_EX_2.reset_index(drop='True')

In [10]:
DUST.tail()

            지역     망 측정소명        측정일시  PM10  PM25                         주소
331819  인천 옹진군  도시대기   영흥  2020053120  31.0  24.0  인천광역시 옹진군 영흥면 영흥로251번길 90
331820  인천 옹진군  도시대기   영흥  2020053121  32.0  24.0  인천광역시 옹진군 영흥면 영흥로251번길 90
331821  인천 옹진군  도시대기   영흥  2020053122  34.0  28.0  인천광역시 옹진군 영흥면 영흥로251번길 90
331822  인천 옹진군  도시대기   영흥  2020053123  29.0  22.0  인천광역시 옹진군 영흥면 영흥로251번길 90
331823  인천 옹진군  도시대기   영흥  2020053124  22.0  21.0  인천광역시 옹진군 영흥면 영흥로251번길 90

In [11]:
DUST.to_csv('data/202005.csv',sep=',')

In [12]:
# 데이터 파일 읽어오기 #6월
DUST = pd.read_csv('2020년 6월.csv', encoding='euc-kr')

In [13]:
DUST.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375489 entries, 0 to 375488
Data columns (total 12 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   지역      375489 non-null  object
 1   망       375489 non-null  object
 2   측정소코드   375489 non-null  int64
 3   측정소명    375489 non-null  object
 4   측정일시    375489 non-null  int64
 5   SO2     357009 non-null  float64
 6   CO      357017 non-null  float64
 7   O3      359589 non-null  float64
 8   NO2     358106 non-null  float64
 9   PM10    355564 non-null  float64
 10  PM25    351809 non-null  float64
 11  주소      375489 non-null  object
dtypes: float64(6), int64(2), object(4)
memory usage: 34.4+ MB

In [14]:
DUST.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 중구,도시대기,111121,중구,2020060101,0.002,0.3,0.032,0.011,33.0,15.0,서울 중구 덕수궁길 15
1,서울 중구,도시대기,111121,중구,2020060102,0.002,0.3,0.034,0.007,17.0,12.0,서울 중구 덕수궁길 15
2,서울 중구,도시대기,111121,중구,2020060103,0.002,0.3,0.034,0.007,NaN,12.0,서울 중구 덕수궁길 15
3,서울 중구,도시대기,111121,중구,2020060104,0.002,0.3,0.035,0.006,13.0,12.0,서울 중구 덕수궁길 15
4,서울 중구,도시대기,111121,중구,2020060105,0.002,0.3,0.034,0.007,11.0,10.0,서울 중구 덕수궁길 15

In [15]:
DUST_EX=DUST[['지역','망','측정소명','측정일시','PM10','PM25','주소']] # df=df1[['지역', '망','측정소명','측정일시','PM10','PM25','주소']]

In [16]:
DUST_EX_2=DUST_EX[DUST_EX['망']=='도시대기'] #도시대기만 뽑아오기

In [17]:
DUST = DUST_EX_2.reset_index(drop='True')

In [18]:
DUST.tail()

            지역     망 측정소명        측정일시  PM10  PM25                         주소
324018  인천 옹진군  도시대기   영흥  2020063020   3.0   NaN  인천광역시 옹진군 영흥면 영흥로251번길 90
324019  인천 옹진군  도시대기   영흥  2020063021   3.0   NaN  인천광역시 옹진군 영흥면 영흥로251번길 90
324020  인천 옹진군  도시대기   영흥  2020063022   3.0   2.0  인천광역시 옹진군 영흥면 영흥로251번길 90
324021  인천 옹진군  도시대기   영흥  2020063023   NaN   3.0  인천광역시 옹진군 영흥면 영흥로251번길 90
324022  인천 옹진군  도시대기   영흥  2020063024   NaN   2.0  인천광역시 옹진군 영흥면 영흥로251번길 90

In [19]:
DUST.to_csv('data/202006.csv',sep=',')

In [4]:
# 데이터 파일 읽어오기 #7월
DUST = pd.read_csv('2020년 7월.csv', encoding='euc-kr')

In [5]:
DUST.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390465 entries, 0 to 390464
Data columns (total 12 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   지역      390465 non-null  object
 1   망       390465 non-null  object
 2   측정소코드   390465 non-null  int64
 3   측정소명    390465 non-null  object
 4   측정일시    390465 non-null  int64
 5   SO2     371186 non-null  float64
 6   CO      373538 non-null  float64
 7   O3      375387 non-null  float64
 8   NO2     376084 non-null  float64
 9   PM10    367804 non-null  float64
 10  PM25    361776 non-null  float64
 11  주소      390465 non-null  object
dtypes: float64(6), int64(2), object(4)
memory usage: 35.7+ MB

In [6]:
DUST.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 중구,도시대기,111121,중구,2020070101,0.002,0.3,0.030,0.009,3.0,4.0,서울 중구 덕수궁길 15
1,서울 중구,도시대기,111121,중구,2020070102,0.002,0.3,0.028,0.009,7.0,4.0,서울 중구 덕수궁길 15
2,서울 중구,도시대기,111121,중구,2020070103,0.002,0.3,0.029,0.007,5.0,5.0,서울 중구 덕수궁길 15
3,서울 중구,도시대기,111121,중구,2020070104,0.002,0.2,0.025,0.008,6.0,2.0,서울 중구 덕수궁길 15
4,서울 중구,도시대기,111121,중구,2020070105,0.002,0.3,0.011,0.018,6.0,4.0,서울 중구 덕수궁길 15

In [7]:
DUST_EX=DUST[['지역','망','측정소명','측정일시','PM10','PM25','주소']] # df=df1[['지역', '망','측정소명','측정일시','PM10','PM25','주소']]

In [8]:
DUST_EX_2=DUST_EX[DUST_EX['망']=='도시대기'] #도시대기만 뽑아오기

In [9]:
DUST = DUST_EX_2.reset_index(drop='True')

In [10]:
DUST.tail()

            지역     망 측정소명        측정일시  PM10  PM25                         주소
336892  인천 옹진군  도시대기   영흥  2020073120  11.0   4.0  인천광역시 옹진군 영흥면 영흥로251번길 90
336893  인천 옹진군  도시대기   영흥  2020073121  10.0   5.0  인천광역시 옹진군 영흥면 영흥로251번길 90
336894  인천 옹진군  도시대기   영흥  2020073122   6.0   NaN  인천광역시 옹진군 영흥면 영흥로251번길 90
336895  인천 옹진군  도시대기   영흥  2020073123   8.0   7.0  인천광역시 옹진군 영흥면 영흥로251번길 90
336896  인천 옹진군  도시대기   영흥  2020073124  13.0   6.0  인천광역시 옹진군 영흥면 영흥로251번길 90

In [11]:
DUST.to_csv('data/202007.csv',sep=',')

In [28]:
# 데이터 파일 읽어오기 #8월
DUST = pd.read_csv('2020년 8월.csv', encoding='euc-kr')

In [29]:
DUST.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396419 entries, 0 to 396418
Data columns (total 12 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   지역      396419 non-null  object
 1   망       396419 non-null  object
 2   측정소코드   396419 non-null  int64
 3   측정소명    396419 non-null  object
 4   측정일시    396419 non-null  int64
 5   SO2     370368 non-null  float64
 6   CO      370554 non-null  float64
 7   O3      370789 non-null  float64
 8   NO2     373216 non-null  float64
 9   PM10    370724 non-null  float64
 10  PM25    361234 non-null  float64
 11  주소      396419 non-null  object
dtypes: float64(6), int64(2), object(4)
memory usage: 36.3+ MB

In [30]:
DUST.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 중구,도시대기,111121,중구,2020080101,0.003,0.2,0.010,0.008,8.0,10.0,서울 중구 덕수궁길 15
1,서울 중구,도시대기,111121,중구,2020080102,0.002,0.2,0.008,0.009,4.0,1.0,서울 중구 덕수궁길 15
2,서울 중구,도시대기,111121,중구,2020080103,0.002,0.3,0.005,0.012,5.0,3.0,서울 중구 덕수궁길 15
3,서울 중구,도시대기,111121,중구,2020080104,0.002,0.3,0.005,0.013,9.0,5.0,서울 중구 덕수궁길 15
4,서울 중구,도시대기,111121,중구,2020080105,0.002,0.3,0.005,0.014,8.0,4.0,서울 중구 덕수궁길 15

In [31]:
DUST_EX=DUST[['지역','망','측정소명','측정일시','PM10','PM25','주소']] # df=df1[['지역', '망','측정소명','측정일시','PM10','PM25','주소']]

In [32]:
DUST_EX_2=DUST_EX[DUST_EX['망']=='도시대기'] #도시대기만 뽑아오기

In [33]:
DUST = DUST_EX_2.reset_index(drop='True')

In [34]:
DUST.tail()

            지역     망 측정소명        측정일시  PM10  PM25                         주소
339870  인천 옹진군  도시대기   영흥  2020083120  11.0   8.0  인천광역시 옹진군 영흥면 영흥로251번길 90
339871  인천 옹진군  도시대기   영흥  2020083121  11.0   5.0  인천광역시 옹진군 영흥면 영흥로251번길 90
339872  인천 옹진군  도시대기   영흥  2020083122  17.0   5.0  인천광역시 옹진군 영흥면 영흥로251번길 90
339873  인천 옹진군  도시대기   영흥  2020083123   8.0   4.0  인천광역시 옹진군 영흥면 영흥로251번길 90
339874  인천 옹진군  도시대기   영흥  2020083124   8.0   2.0  인천광역시 옹진군 영흥면 영흥로251번길 90

In [35]:
DUST.to_csv('data/202008.csv',sep=',')

In [36]:
# 데이터 파일 읽어오기 #9월
DUST = pd.read_csv('2020년 9월.csv', encoding='euc-kr')

In [37]:
DUST.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391180 entries, 0 to 391179
Data columns (total 12 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   지역      391180 non-null  object
 1   망       391180 non-null  object
 2   측정소코드   391180 non-null  int64
 3   측정소명    391180 non-null  object
 4   측정일시    391180 non-null  int64
 5   SO2     354182 non-null  float64
 6   CO      356207 non-null  float64
 7   O3      357268 non-null  float64
 8   NO2     357516 non-null  float64
 9   PM10    347588 non-null  float64
 10  PM25    342024 non-null  float64
 11  주소      391180 non-null  object
dtypes: float64(6), int64(2), object(4)
memory usage: 35.8+ MB

In [38]:
DUST.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 중구,도시대기,111121,중구,2020090101,0.002,0.4,0.015,0.015,7.0,5.0,서울 중구 덕수궁길 15
1,서울 중구,도시대기,111121,중구,2020090102,0.003,0.4,0.016,0.014,11.0,5.0,서울 중구 덕수궁길 15
2,서울 중구,도시대기,111121,중구,2020090103,0.003,0.4,0.014,0.014,10.0,8.0,서울 중구 덕수궁길 15
3,서울 중구,도시대기,111121,중구,2020090104,0.003,0.4,0.014,0.015,8.0,5.0,서울 중구 덕수궁길 15
4,서울 중구,도시대기,111121,중구,2020090105,0.003,0.4,0.014,0.015,9.0,7.0,서울 중구 덕수궁길 15

In [39]:
DUST_EX=DUST[['지역','망','측정소명','측정일시','PM10','PM25','주소']] # df=df1[['지역', '망','측정소명','측정일시','PM10','PM25','주소']]

In [40]:
DUST_EX_2=DUST_EX[DUST_EX['망']=='도시대기'] #도시대기만 뽑아오기

In [41]:
DUST = DUST_EX_2.reset_index(drop='True')

In [42]:
DUST.tail()

            지역     망 측정소명        측정일시  PM10  PM25                         주소
330569  인천 옹진군  도시대기   영흥  2020093020  24.0  14.0  인천광역시 옹진군 영흥면 영흥로251번길 90
330570  인천 옹진군  도시대기   영흥  2020093021  25.0  17.0  인천광역시 옹진군 영흥면 영흥로251번길 90
330571  인천 옹진군  도시대기   영흥  2020093022  20.0  12.0  인천광역시 옹진군 영흥면 영흥로251번길 90
330572  인천 옹진군  도시대기   영흥  2020093023  22.0  14.0  인천광역시 옹진군 영흥면 영흥로251번길 90
330573  인천 옹진군  도시대기   영흥  2020093024  24.0  16.0  인천광역시 옹진군 영흥면 영흥로251번길 90

In [43]:
DUST.to_csv('data/202009.csv',sep=',')

In [44]:
# 데이터 파일 읽어오기 #10월
DUST = pd.read_csv('2020년 10월.csv', encoding='euc-kr')

In [45]:
DUST.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 408621 entries, 0 to 408620
Data columns (total 12 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   지역      408621 non-null  object
 1   망       408621 non-null  object
 2   측정소코드   408621 non-null  int64
 3   측정소명    408621 non-null  object
 4   측정일시    408621 non-null  int64
 5   SO2     380916 non-null  float64
 6   CO      380195 non-null  float64
 7   O3      379985 non-null  float64
 8   NO2     381826 non-null  float64
 9   PM10    367302 non-null  float64
 10  PM25    365013 non-null  float64
 11  주소      408621 non-null  object
dtypes: float64(6), int64(2), object(4)
memory usage: 37.4+ MB

In [46]:
DUST.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 중구,도시대기,111121,중구,2020100101,0.003,0.3,0.020,0.012,16.0,8.0,서울 중구 덕수궁길 15
1,서울 중구,도시대기,111121,중구,2020100102,0.002,0.3,0.025,0.007,8.0,4.0,서울 중구 덕수궁길 15
2,서울 중구,도시대기,111121,중구,2020100103,0.002,0.3,0.022,0.008,8.0,3.0,서울 중구 덕수궁길 15
3,서울 중구,도시대기,111121,중구,2020100104,0.002,0.3,0.023,0.007,7.0,4.0,서울 중구 덕수궁길 15
4,서울 중구,도시대기,111121,중구,2020100105,0.003,0.3,0.024,0.006,7.0,5.0,서울 중구 덕수궁길 15

In [47]:
DUST_EX=DUST[['지역','망','측정소명','측정일시','PM10','PM25','주소']] # df=df1[['지역', '망','측정소명','측정일시','PM10','PM25','주소']]

In [48]:
DUST_EX_2=DUST_EX[DUST_EX['망']=='도시대기'] #도시대기만 뽑아오기

In [49]:
DUST = DUST_EX_2.reset_index(drop='True')

In [50]:
DUST.tail()

            지역     망 측정소명        측정일시  PM10  PM25                         주소
345313  인천 옹진군  도시대기   영흥  2020103120  24.0   7.0  인천광역시 옹진군 영흥면 영흥로251번길 90
345314  인천 옹진군  도시대기   영흥  2020103121  22.0  10.0  인천광역시 옹진군 영흥면 영흥로251번길 90
345315  인천 옹진군  도시대기   영흥  2020103122  30.0   9.0  인천광역시 옹진군 영흥면 영흥로251번길 90
345316  인천 옹진군  도시대기   영흥  2020103123  25.0  10.0  인천광역시 옹진군 영흥면 영흥로251번길 90
345317  인천 옹진군  도시대기   영흥  2020103124  22.0  12.0  인천광역시 옹진군 영흥면 영흥로251번길 90

In [51]:
DUST.to_csv('data/202010.csv',sep=',')

In [52]:
# 데이터 파일 읽어오기 #11월
DUST = pd.read_csv('2020년 11월.csv', encoding='euc-kr')

In [53]:
DUST.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 402415 entries, 0 to 402414
Data columns (total 12 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   지역      402415 non-null  object
 1   망       402415 non-null  object
 2   측정소코드   402415 non-null  int64
 3   측정소명    402415 non-null  object
 4   측정일시    402415 non-null  int64
 5   SO2     374043 non-null  float64
 6   CO      372568 non-null  float64
 7   O3      374286 non-null  float64
 8   NO2     375386 non-null  float64
 9   PM10    361391 non-null  float64
 10  PM25    360221 non-null  float64
 11  주소      402415 non-null  object
dtypes: float64(6), int64(2), object(4)
memory usage: 36.8+ MB

In [54]:
DUST.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 중구,도시대기,111121,중구,2020110101,0.004,0.4,0.031,0.019,31.0,17.0,서울 중구 덕수궁길 15
1,서울 중구,도시대기,111121,중구,2020110102,0.003,0.4,0.032,0.016,31.0,14.0,서울 중구 덕수궁길 15
2,서울 중구,도시대기,111121,중구,2020110103,0.003,0.4,0.033,0.014,35.0,17.0,서울 중구 덕수궁길 15
3,서울 중구,도시대기,111121,중구,2020110104,0.003,0.3,0.034,0.013,28.0,17.0,서울 중구 덕수궁길 15
4,서울 중구,도시대기,111121,중구,2020110105,0.003,0.4,0.031,0.015,31.0,14.0,서울 중구 덕수궁길 15

In [55]:
DUST_EX=DUST[['지역','망','측정소명','측정일시','PM10','PM25','주소']] # df=df1[['지역', '망','측정소명','측정일시','PM10','PM25','주소']]

In [56]:
DUST_EX_2=DUST_EX[DUST_EX['망']=='도시대기'] #도시대기만 뽑아오기

In [57]:
DUST = DUST_EX_2.reset_index(drop='True')

In [58]:
DUST.tail()

            지역     망 측정소명        측정일시  PM10  PM25                         주소
339770  인천 옹진군  도시대기   영흥  2020113020  14.0  12.0  인천광역시 옹진군 영흥면 영흥로251번길 90
339771  인천 옹진군  도시대기   영흥  2020113021  21.0  15.0  인천광역시 옹진군 영흥면 영흥로251번길 90
339772  인천 옹진군  도시대기   영흥  2020113022  21.0  10.0  인천광역시 옹진군 영흥면 영흥로251번길 90
339773  인천 옹진군  도시대기   영흥  2020113023  18.0  15.0  인천광역시 옹진군 영흥면 영흥로251번길 90
339774  인천 옹진군  도시대기   영흥  2020113024  14.0  12.0  인천광역시 옹진군 영흥면 영흥로251번길 90

In [59]:
DUST.to_csv('data/202011.csv',sep=',')

In [60]:
# 데이터 파일 읽어오기 #12월
DUST = pd.read_csv('2020년 12월.csv', encoding='euc-kr')

In [61]:
DUST.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418584 entries, 0 to 418583
Data columns (total 12 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   지역      418584 non-null  object
 1   망       418584 non-null  object
 2   측정소코드   418584 non-null  int64
 3   측정소명    418584 non-null  object
 4   측정일시    418584 non-null  int64
 5   SO2     397460 non-null  float64
 6   CO      397084 non-null  float64
 7   O3      396856 non-null  float64
 8   NO2     398664 non-null  float64
 9   PM10    391445 non-null  float64
 10  PM25    386352 non-null  float64
 11  주소      418584 non-null  object
dtypes: float64(6), int64(2), object(4)
memory usage: 38.3+ MB

In [62]:
DUST.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 중구,도시대기,111121,중구,2020120101,0.003,0.6,0.017,0.024,50.0,26.0,서울 중구 덕수궁길 15
1,서울 중구,도시대기,111121,중구,2020120102,0.003,0.5,0.024,0.015,42.0,24.0,서울 중구 덕수궁길 15
2,서울 중구,도시대기,111121,중구,2020120103,0.003,0.4,0.026,0.013,36.0,19.0,서울 중구 덕수궁길 15
3,서울 중구,도시대기,111121,중구,2020120104,0.003,0.5,0.023,0.015,34.0,17.0,서울 중구 덕수궁길 15
4,서울 중구,도시대기,111121,중구,2020120105,0.003,0.5,0.017,0.022,36.0,18.0,서울 중구 덕수궁길 15

In [63]:
DUST_EX=DUST[['지역','망','측정소명','측정일시','PM10','PM25','주소']] # df=df1[['지역', '망','측정소명','측정일시','PM10','PM25','주소']]

In [64]:
DUST_EX_2=DUST_EX[DUST_EX['망']=='도시대기'] #도시대기만 뽑아오기

In [65]:
DUST = DUST_EX_2.reset_index(drop='True')

In [66]:
DUST.tail()

            지역     망 측정소명        측정일시  PM10  PM25                         주소
353107  인천 옹진군  도시대기   영흥  2020123120  20.0   9.0  인천광역시 옹진군 영흥면 영흥로251번길 90
353108  인천 옹진군  도시대기   영흥  2020123121  20.0  10.0  인천광역시 옹진군 영흥면 영흥로251번길 90
353109  인천 옹진군  도시대기   영흥  2020123122  16.0   8.0  인천광역시 옹진군 영흥면 영흥로251번길 90
353110  인천 옹진군  도시대기   영흥  2020123123  14.0  12.0  인천광역시 옹진군 영흥면 영흥로251번길 90
353111  인천 옹진군  도시대기   영흥  2020123124  15.0   8.0  인천광역시 옹진군 영흥면 영흥로251번길 90

In [67]:
DUST.to_csv('data/202012.csv',sep=',')

In [68]:
# 데이터 파일 읽어오기 #12월
DUST = pd.read_csv('data/202012.csv', encoding='UTF-8', index_col=0)

In [69]:
DUST.head()

      지역     망 측정소명        측정일시  PM10  PM25             주소
0  서울 중구  도시대기   중구  2020120101  50.0  26.0  서울 중구 덕수궁길 15
1  서울 중구  도시대기   중구  2020120102  42.0  24.0  서울 중구 덕수궁길 15
2  서울 중구  도시대기   중구  2020120103  36.0  19.0  서울 중구 덕수궁길 15
3  서울 중구  도시대기   중구  2020120104  34.0  17.0  서울 중구 덕수궁길 15
4  서울 중구  도시대기   중구  2020120105  36.0  18.0  서울 중구 덕수궁길 15

In [70]:
DUST.head()

      지역     망 측정소명        측정일시  PM10  PM25             주소
0  서울 중구  도시대기   중구  2020120101  50.0  26.0  서울 중구 덕수궁길 15
1  서울 중구  도시대기   중구  2020120102  42.0  24.0  서울 중구 덕수궁길 15
2  서울 중구  도시대기   중구  2020120103  36.0  19.0  서울 중구 덕수궁길 15
3  서울 중구  도시대기   중구  2020120104  34.0  17.0  서울 중구 덕수궁길 15
4  서울 중구  도시대기   중구  2020120105  36.0  18.0  서울 중구 덕수궁길 15

In [71]:
DUST.head(26)

       지역     망 측정소명        측정일시  PM10  PM25             주소
0   서울 중구  도시대기   중구  2020120101  50.0  26.0  서울 중구 덕수궁길 15
1   서울 중구  도시대기   중구  2020120102  42.0  24.0  서울 중구 덕수궁길 15
2   서울 중구  도시대기   중구  2020120103  36.0  19.0  서울 중구 덕수궁길 15
3   서울 중구  도시대기   중구  2020120104  34.0  17.0  서울 중구 덕수궁길 15
4   서울 중구  도시대기   중구  2020120105  36.0  18.0  서울 중구 덕수궁길 15
5   서울 중구  도시대기   중구  2020120106  36.0  17.0  서울 중구 덕수궁길 15
6   서울 중구  도시대기   중구  2020120107  46.0  21.0  서울 중구 덕수궁길 15
7   서울 중구  도시대기   중구  2020120108  43.0  21.0  서울 중구 덕수궁길 15
8   서울 중구  도시대기   중구  2020120109  45.0  21.0  서울 중구 덕수궁길 15
9   서울 중구  도시대기   중구  2020120110  47.0  23.0  서울 중구 덕수궁길 15
10  서울 중구  도시대기   중구  2020120111  45.0  26.0  서울 중구 덕수궁길 15
11  서울 중구  도시대기   중구  2020120112  34.0  19.0  서울 중구 덕수궁길 15
12  서울 중구  도시대기   중구  2020120113  33.0  15.0  서울 중구 덕수궁길 15
13  서울 중구  도시대기   중구  2020120114  32.0  19.0  서울 중구 덕수궁길 15
14  서울 중구  도시대기   중구  2020120115  35.0  21.0  서울 중구 덕수궁길 15
15  서울 중구  도시대기   중구  2020120116  21.0  10.0  서울 중구 덕수궁길 15
16  서울 중구  도시대기   중구  2020120117  23.0  12.0  서울 중구 덕수궁길 15
17  서울 중구  도시대기   중구  2020120118  30.0  17.0  서울 중구 덕수궁길 15
18  서울 중구  도시대기   중구  2020120119  35.0  20.0  서울 중구 덕수궁길 15
19  서울 중구  도시대기   중구  2020120120  35.0  19.0  서울 중구 덕수궁길 15
20  서울 중구  도시대기   중구  2020120121  38.0  22.0  서울 중구 덕수궁길 15
21  서울 중구  도시대기   중구  2020120122  38.0  20.0  서울 중구 덕수궁길 15
22  서울 중구  도시대기   중구  2020120123  39.0  22.0  서울 중구 덕수궁길 15
23  서울 중구  도시대기   중구  2020120124  39.0  20.0  서울 중구 덕수궁길 15
24  서울 중구  도시대기   중구  2020120201  38.0  20.0  서울 중구 덕수궁길 15
25  서울 중구  도시대기   중구  2020120202  38.0  19.0  서울 중구 덕수궁길 15

In [72]:
DUST['측정일시']=DUST['측정일시'].astype('str')

In [73]:
# 측정일시 정규화하기
dust_date = []

for date in DUST['측정일시']:
        dust_date.append(str(date) + '0000')

In [74]:
dust_date

['20201201010000',
 '20201201020000',
 '20201201030000',
 '20201201040000',
 '20201201050000',
 '20201201060000',
 '20201201070000',
 '20201201080000',
 '20201201090000',
 '20201201100000',
 '20201201110000',
 '20201201120000',
 '20201201130000',
 '20201201140000',
 '20201201150000',
 '20201201160000',
 '20201201170000',
 '20201201180000',
 '20201201190000',
 '20201201200000',
 '20201201210000',
 '20201201220000',
 '20201201230000',
 '20201201240000',
 '20201202010000',
 '20201202020000',
 '20201202030000',
 '20201202040000',
 '20201202050000',
 '20201202060000',
 '20201202070000',
 '20201202080000',
 '20201202090000',
 '20201202100000',
 '20201202110000',
 '20201202120000',
 '20201202130000',
 '20201202140000',
 '20201202150000',
 '20201202160000',
 '20201202170000',
 '20201202180000',
 '20201202190000',
 '20201202200000',
 '20201202210000',
 '20201202220000',
 '20201202230000',
 '20201202240000',
 '20201203010000',
 '20201203020000',
 '20201203030000',
 '20201203040000',
 '20201203050000',
 '20201203060000',
 '20201203070000',
 '20201203080000',
 '20201203090000',
 '20201203100000',
 '20201203110000',
 '20201203120000',
 '20201203130000',
 '20201203140000',
 '20201203150000',
 '20201203160000',
 '20201203170000',
 '20201203180000',
 '20201203190000',
 '20201203200000',
 '20201203210000',
 '20201203220000',
 '20201203230000',
 '20201203240000',
 '20201204010000',
 '20201204020000',
 '20201204030000',
 '20201204040000',
 '20201204050000',
 '20201204060000',
 '20201204070000',
 '20201204080000',
 '20201204090000',
 '20201204100000',
 '20201204110000',
 '20201204120000',
 '20201204130000',
 '20201204140000',
 '20201204150000',
 '20201204160000',
 '20201204170000',
 '20201204180000',
 '20201204190000',
 '20201204200000',
 '20201204210000',
 '20201204220000',
 '20201204230000',
 '20201204240000',
 '20201205010000',
 '20201205020000',
 '20201205030000',
 '20201205040000',
 '20201205050000',
 '20201205060000',
 '20201205070000',
 '20201205080000',
 '20201205090000',
 '20201205100000',
 '20201205110000',
 '20201205120000',
 '20201205130000',
 '20201205140000',
 '20201205150000',
 '20201205160000',
 '20201205170000',
 '20201205180000',
 '20201205190000',
 '20201205200000',
 '20201205210000',
 '20201205220000',
 '20201205230000',
 '20201205240000',
 '20201206010000',
 '20201206020000',
 '20201206030000',
 '20201206040000',
 '20201206050000',
 '20201206060000',
 '20201206070000',
 '20201206080000',
 '20201206090000',
 '20201206100000',
 '20201206110000',
 '20201206120000',
 '20201206130000',
 '20201206140000',
 '20201206150000',
 '20201206160000',
 '20201206170000',
 '20201206180000',
 '20201206190000',
 '20201206200000',
 '20201206210000',
 '20201206220000',
 '20201206230000',
 '20201206240000',
 '20201207010000',
 '20201207020000',
 '20201207030000',
 '20201207040000',
 '20201207050000',
 '20201207060000',
 '20201207070000',
 '20201207080000',
 '20201207090000',
 '20201207100000',
 '20201207110000',
 '20201207120000',
 '20201207130000',
 '20201207140000',
 '20201207150000',
 '20201207160000',
 '20201207170000',
 '20201207180000',
 '20201207190000',
 '20201207200000',
 '20201207210000',
 '20201207220000',
 '20201207230000',
 '20201207240000',
 '20201208010000',
 '20201208020000',
 '20201208030000',
 '20201208040000',
 '20201208050000',
 '20201208060000',
 '20201208070000',
 '20201208080000',
 '20201208090000',
 '20201208100000',
 '20201208110000',
 '20201208120000',
 '20201208130000',
 '20201208140000',
 '20201208150000',
 '20201208160000',
 '20201208170000',
 '20201208180000',
 '20201208190000',
 '20201208200000',
 '20201208210000',
 '20201208220000',
 '20201208230000',
 '20201208240000',
 '20201209010000',
 '20201209020000',
 '20201209030000',
 '20201209040000',
 '20201209050000',
 '20201209060000',
 '20201209070000',
 '20201209080000',
 '20201209090000',
 '20201209100000',
 '20201209110000',
 '20201209120000',
 '20201209130000',
 '20201209140000',
 '20201209150000',
 '20201209160000',
 '20201209170000',
 '20201209180000',
 '20201209190000',
 '20201209200000',
 '20201209210000',
 '20201209220000',
 '20201209230000',
 '20201209240000',
 '20201210010000',
 '20201210020000',
 '20201210030000',
 '20201210040000',
 '20201210050000',
 '20201210060000',
 '20201210070000',
 '20201210080000',
 '20201210090000',
 '20201210100000',
 '20201210110000',
 '20201210120000',
 '20201210130000',
 '20201210140000',
 '20201210150000',
 '20201210160000',
 '20201210170000',
 '20201210180000',
 '20201210190000',
 '20201210200000',
 '20201210210000',
 '20201210220000',
 '20201210230000',
 '20201210240000',
 '20201211010000',
 '20201211020000',
 '20201211030000',
 '20201211040000',
 '20201211050000',
 '20201211060000',
 '20201211070000',
 '20201211080000',
 '20201211090000',
 '20201211100000',
 '20201211110000',
 '20201211120000',
 '20201211130000',
 '20201211140000',
 '20201211150000',
 '20201211160000',
 '20201211170000',
 '20201211180000',
 '20201211190000',
 '20201211200000',
 '20201211210000',
 '20201211220000',
 '20201211230000',
 '20201211240000',
 '20201212010000',
 '20201212020000',
 '20201212030000',
 '20201212040000',
 '20201212050000',
 '20201212060000',
 '20201212070000',
 '20201212080000',
 '20201212090000',
 '20201212100000',
 '20201212110000',
 '20201212120000',
 '20201212130000',
 '20201212140000',
 '20201212150000',
 '20201212160000',
 '20201212170000',
 '20201212180000',
 '20201212190000',
 '20201212200000',
 '20201212210000',
 '20201212220000',
 '20201212230000',
 '20201212240000',
 '20201213010000',
 '20201213020000',
 '20201213030000',
 '20201213040000',
 '20201213050000',
 '20201213060000',
 '20201213070000',
 '20201213080000',
 '20201213090000',
 '20201213100000',
 '20201213110000',
 '20201213120000',
 '20201213130000',
 '20201213140000',
 '20201213150000',
 '20201213160000',
 '20201213170000',
 '20201213180000',
 '20201213190000',
 '20201213200000',
 '20201213210000',
 '20201213220000',
 '20201213230000',
 '20201213240000',
 '20201214010000',
 '20201214020000',
 '20201214030000',
 '20201214040000',
 '20201214050000',
 '20201214060000',
 '20201214070000',
 '20201214080000',
 '20201214090000',
 '20201214100000',
 '20201214110000',
 '20201214120000',
 '20201214130000',
 '20201214140000',
 '20201214150000',
 '20201214160000',
 '20201214170000',
 '20201214180000',
 '20201214190000',
 '20201214200000',
 '20201214210000',
 '20201214220000',
 '20201214230000',
 '20201214240000',
 '20201215010000',
 '20201215020000',
 '20201215030000',
 '20201215040000',
 '20201215050000',
 '20201215060000',
 '20201215070000',
 '20201215080000',
 '20201215090000',
 '20201215100000',
 '20201215110000',
 '20201215120000',
 '20201215130000',
 '20201215140000',
 '20201215150000',
 '20201215160000',
 '20201215170000',
 '20201215180000',
 '20201215190000',
 '20201215200000',
 '20201215210000',
 '20201215220000',
 '20201215230000',
 '20201215240000',
 '20201216010000',
 '20201216020000',
 '20201216030000',
 '20201216040000',
 '20201216050000',
 '20201216060000',
 '20201216070000',
 '20201216080000',
 '20201216090000',
 '20201216100000',
 '20201216110000',
 '20201216120000',
 '20201216130000',
 '20201216140000',
 '20201216150000',
 '20201216160000',
 '20201216170000',
 '20201216180000',
 '20201216190000',
 '20201216200000',
 '20201216210000',
 '20201216220000',
 '20201216230000',
 '20201216240000',
 '20201217010000',
 '20201217020000',
 '20201217030000',
 '20201217040000',
 '20201217050000',
 '20201217060000',
 '20201217070000',
 '20201217080000',
 '20201217090000',
 '20201217100000',
 '20201217110000',
 '20201217120000',
 '20201217130000',
 '20201217140000',
 '20201217150000',
 '20201217160000',
 '20201217170000',
 '20201217180000',
 '20201217190000',
 '20201217200000',
 '20201217210000',
 '20201217220000',
 '20201217230000',
 '20201217240000',
 '20201218010000',
 '20201218020000',
 '20201218030000',
 '20201218040000',
 '20201218050000',
 '20201218060000',
 '20201218070000',
 '20201218080000',
 '20201218090000',
 '20201218100000',
 '20201218110000',
 '20201218120000',
 '20201218130000',
 '20201218140000',
 '20201218150000',
 '20201218160000',
 '20201218170000',
 '20201218180000',
 '20201218190000',
 '20201218200000',
 '20201218210000',
 '20201218220000',
 '20201218230000',
 '20201218240000',
 '20201219010000',
 '20201219020000',
 '20201219030000',
 '20201219040000',
 '20201219050000',
 '20201219060000',
 '20201219070000',
 '20201219080000',
 '20201219090000',
 '20201219100000',
 '20201219110000',
 '20201219120000',
 '20201219130000',
 '20201219140000',
 '20201219150000',
 '20201219160000',
 '20201219170000',
 '20201219180000',
 '20201219190000',
 '20201219200000',
 '20201219210000',
 '20201219220000',
 '20201219230000',
 '20201219240000',
 '20201220010000',
 '20201220020000',
 '20201220030000',
 '20201220040000',
 '20201220050000',
 '20201220060000',
 '20201220070000',
 '20201220080000',
 '20201220090000',
 '20201220100000',
 '20201220110000',
 '20201220120000',
 '20201220130000',
 '20201220140000',
 '20201220150000',
 '20201220160000',
 '20201220170000',
 '20201220180000',
 '20201220190000',
 '20201220200000',
 '20201220210000',
 '20201220220000',
 '20201220230000',
 '20201220240000',
 '20201221010000',
 '20201221020000',
 '20201221030000',
 '20201221040000',
 '20201221050000',
 '20201221060000',
 '20201221070000',
 '20201221080000',
 '20201221090000',
 '20201221100000',
 '20201221110000',
 '20201221120000',
 '20201221130000',
 '20201221140000',
 '20201221150000',
 '20201221160000',
 '20201221170000',
 '20201221180000',
 '20201221190000',
 '20201221200000',
 '20201221210000',
 '20201221220000',
 '20201221230000',
 '20201221240000',
 '20201222010000',
 '20201222020000',
 '20201222030000',
 '20201222040000',
 '20201222050000',
 '20201222060000',
 '20201222070000',
 '20201222080000',
 '20201222090000',
 '20201222100000',
 '20201222110000',
 '20201222120000',
 '20201222130000',
 '20201222140000',
 '20201222150000',
 '20201222160000',
 '20201222170000',
 '20201222180000',
 '20201222190000',
 '20201222200000',
 '20201222210000',
 '20201222220000',
 '20201222230000',
 '20201222240000',
 '20201223010000',
 '20201223020000',
 '20201223030000',
 '20201223040000',
 '20201223050000',
 '20201223060000',
 '20201223070000',
 '20201223080000',
 '20201223090000',
 '20201223100000',
 '20201223110000',
 '20201223120000',
 '20201223130000',
 '20201223140000',
 '20201223150000',
 '20201223160000',
 '20201223170000',
 '20201223180000',
 '20201223190000',
 '20201223200000',
 '20201223210000',
 '20201223220000',
 '20201223230000',
 '20201223240000',
 '20201224010000',
 '20201224020000',
 '20201224030000',
 '20201224040000',
 '20201224050000',
 '20201224060000',
 '20201224070000',
 '20201224080000',
 '20201224090000',
 '20201224100000',
 '20201224110000',
 '20201224120000',
 '20201224130000',
 '20201224140000',
 '20201224150000',
 '20201224160000',
 '20201224170000',
 '20201224180000',
 '20201224190000',
 '20201224200000',
 '20201224210000',
 '20201224220000',
 '20201224230000',
 '20201224240000',
 '20201225010000',
 '20201225020000',
 '20201225030000',
 '20201225040000',
 '20201225050000',
 '20201225060000',
 '20201225070000',
 '20201225080000',
 '20201225090000',
 '20201225100000',
 '20201225110000',
 '20201225120000',
 '20201225130000',
 '20201225140000',
 '20201225150000',
 '20201225160000',
 '20201225170000',
 '20201225180000',
 '20201225190000',
 '20201225200000',
 '20201225210000',
 '20201225220000',
 '20201225230000',
 '20201225240000',
 '20201226010000',
 '20201226020000',
 '20201226030000',
 '20201226040000',
 '20201226050000',
 '20201226060000',
 '20201226070000',
 '20201226080000',
 '20201226090000',
 '20201226100000',
 '20201226110000',
 '20201226120000',
 '20201226130000',
 '20201226140000',
 '20201226150000',
 '20201226160000',
 '20201226170000',
 '20201226180000',
 '20201226190000',
 '20201226200000',
 '20201226210000',
 '20201226220000',
 '20201226230000',
 '20201226240000',
 '20201227010000',
 '20201227020000',
 '20201227030000',
 '20201227040000',
 '20201227050000',
 '20201227060000',
 '20201227070000',
 '20201227080000',
 '20201227090000',
 '20201227100000',
 '20201227110000',
 '20201227120000',
 '20201227130000',
 '20201227140000',
 '20201227150000',
 '20201227160000',
 '20201227170000',
 '20201227180000',
 '20201227190000',
 '20201227200000',
 '20201227210000',
 '20201227220000',
 '20201227230000',
 '20201227240000',
 '20201228010000',
 '20201228020000',
 '20201228030000',
 '20201228040000',
 '20201228050000',
 '20201228060000',
 '20201228070000',
 '20201228080000',
 '20201228090000',
 '20201228100000',
 '20201228110000',
 '20201228120000',
 '20201228130000',
 '20201228140000',
 '20201228150000',
 '20201228160000',
 '20201228170000',
 '20201228180000',
 '20201228190000',
 '20201228200000',
 '20201228210000',
 '20201228220000',
 '20201228230000',
 '20201228240000',
 '20201229010000',
 '20201229020000',
 '20201229030000',
 '20201229040000',
 '20201229050000',
 '20201229060000',
 '20201229070000',
 '20201229080000',
 '20201229090000',
 '20201229100000',
 '20201229110000',
 '20201229120000',
 '20201229130000',
 '20201229140000',
 '20201229150000',
 '20201229160000',
 '20201229170000',
 '20201229180000',
 '20201229190000',
 '20201229200000',
 '20201229210000',
 '20201229220000',
 '20201229230000',
 '20201229240000',
 '20201230010000',
 '20201230020000',
 '20201230030000',
 '20201230040000',
 '20201230050000',
 '20201230060000',
 '20201230070000',
 '20201230080000',
 '20201230090000',
 '20201230100000',
 '20201230110000',
 '20201230120000',
 '20201230130000',
 '20201230140000',
 '20201230150000',
 '20201230160000',
 '20201230170000',
 '20201230180000',
 '20201230190000',
 '20201230200000',
 '20201230210000',
 '20201230220000',
 '20201230230000',
 '20201230240000',
 '20201231010000',
 '20201231020000',
 '20201231030000',
 '20201231040000',
 '20201231050000',
 '20201231060000',
 '20201231070000',
 '20201231080000',
 '20201231090000',
 '20201231100000',
 '20201231110000',
 '20201231120000',
 '20201231130000',
 '20201231140000',
 '20201231150000',
 '20201231160000',
 '20201231170000',
 '20201231180000',
 '20201231190000',
 '20201231200000',
 '20201231210000',
 '20201231220000',
 '20201231230000',
 '20201231240000',
 '20201201010000',
 '20201201020000',
 '20201201030000',
 '20201201040000',
 '20201201050000',
 '20201201060000',
 '20201201070000',
 '20201201080000',
 '20201201090000',
 '20201201100000',
 '20201201110000',
 '20201201120000',
 '20201201130000',
 '20201201140000',
 '20201201150000',
 '20201201160000',
 '20201201170000',
 '20201201180000',
 '20201201190000',
 '20201201200000',
 '20201201210000',
 '20201201220000',
 '20201201230000',
 '20201201240000',
 '20201202010000',
 '20201202020000',
 '20201202030000',
 '20201202040000',
 '20201202050000',
 '20201202060000',
 '20201202070000',
 '20201202080000',
 '20201202090000',
 '20201202100000',
 '20201202110000',
 '20201202120000',
 '20201202130000',
 '20201202140000',
 '20201202150000',
 '20201202160000',
 '20201202170000',
 '20201202180000',
 '20201202190000',
 '20201202200000',
 '20201202210000',
 '20201202220000',
 '20201202230000',
 '20201202240000',
 '20201203010000',
 '20201203020000',
 '20201203030000',
 '20201203040000',
 '20201203050000',
 '20201203060000',
 '20201203070000',
 '20201203080000',
 '20201203090000',
 '20201203100000',
 '20201203110000',
 '20201203120000',
 '20201203130000',
 '20201203140000',
 '20201203150000',
 '20201203160000',
 '20201203170000',
 '20201203180000',
 '20201203190000',
 '20201203200000',
 '20201203210000',
 '20201203220000',
 '20201203230000',
 '20201203240000',
 '20201204010000',
 '20201204020000',
 '20201204030000',
 '20201204040000',
 '20201204050000',
 '20201204060000',
 '20201204070000',
 '20201204080000',
 '20201204090000',
 '20201204100000',
 '20201204110000',
 '20201204120000',
 '20201204130000',
 '20201204140000',
 '20201204150000',
 '20201204160000',
 '20201204170000',
 '20201204180000',
 '20201204190000',
 '20201204200000',
 '20201204210000',
 '20201204220000',
 '20201204230000',
 '20201204240000',
 '20201205010000',
 '20201205020000',
 '20201205030000',
 '20201205040000',
 '20201205050000',
 '20201205060000',
 '20201205070000',
 '20201205080000',
 '20201205090000',
 '20201205100000',
 '20201205110000',
 '20201205120000',
 '20201205130000',
 '20201205140000',
 '20201205150000',
 '20201205160000',
 '20201205170000',
 '20201205180000',
 '20201205190000',
 '20201205200000',
 '20201205210000',
 '20201205220000',
 '20201205230000',
 '20201205240000',
 '20201206010000',
 '20201206020000',
 '20201206030000',
 '20201206040000',
 '20201206050000',
 '20201206060000',
 '20201206070000',
 '20201206080000',
 '20201206090000',
 '20201206100000',
 '20201206110000',
 '20201206120000',
 '20201206130000',
 '20201206140000',
 '20201206150000',
 '20201206160000',
 '20201206170000',
 '20201206180000',
 '20201206190000',
 '20201206200000',
 '20201206210000',
 '20201206220000',
 '20201206230000',
 '20201206240000',
 '20201207010000',
 '20201207020000',
 '20201207030000',
 '20201207040000',
 '20201207050000',
 '20201207060000',
 '20201207070000',
 '20201207080000',
 '20201207090000',
 '20201207100000',
 '20201207110000',
 '20201207120000',
 '20201207130000',
 '20201207140000',
 '20201207150000',
 '20201207160000',
 '20201207170000',
 '20201207180000',
 '20201207190000',
 '20201207200000',
 '20201207210000',
 '20201207220000',
 '20201207230000',
 '20201207240000',
 '20201208010000',
 '20201208020000',
 '20201208030000',
 '20201208040000',
 '20201208050000',
 '20201208060000',
 '20201208070000',
 '20201208080000',
 '20201208090000',
 '20201208100000',
 '20201208110000',
 '20201208120000',
 '20201208130000',
 '20201208140000',
 '20201208150000',
 '20201208160000',
 '20201208170000',
 '20201208180000',
 '20201208190000',
 '20201208200000',
 '20201208210000',
 '20201208220000',
 '20201208230000',
 '20201208240000',
 '20201209010000',
 '20201209020000',
 '20201209030000',
 '20201209040000',
 '20201209050000',
 '20201209060000',
 '20201209070000',
 '20201209080000',
 '20201209090000',
 '20201209100000',
 '20201209110000',
 '20201209120000',
 '20201209130000',
 '20201209140000',
 '20201209150000',
 '20201209160000',
 '20201209170000',
 '20201209180000',
 '20201209190000',
 '20201209200000',
 '20201209210000',
 '20201209220000',
 '20201209230000',
 '20201209240000',
 '20201210010000',
 '20201210020000',
 '20201210030000',
 '20201210040000',
 '20201210050000',
 '20201210060000',
 '20201210070000',
 '20201210080000',
 '20201210090000',
 '20201210100000',
 '20201210110000',
 '20201210120000',
 '20201210130000',
 '20201210140000',
 '20201210150000',
 '20201210160000',
 '20201210170000',
 '20201210180000',
 '20201210190000',
 '20201210200000',
 '20201210210000',
 '20201210220000',
 '20201210230000',
 '20201210240000',
 '20201211010000',
 '20201211020000',
 '20201211030000',
 '20201211040000',
 '20201211050000',
 '20201211060000',
 '20201211070000',
 '20201211080000',
 '20201211090000',
 '20201211100000',
 '20201211110000',
 '20201211120000',
 '20201211130000',
 '20201211140000',
 '20201211150000',
 '20201211160000',
 ...]

In [75]:
date=[]
for i in dust_date:
    date.append(str(i[:4]+'-'+i[4:6]+'-'+i[6:8]+' '+i[8:10]+':'+i[10:12]+':'+i[12:]))
    date
DUST['date']=pd.to_datetime(date)
date
#DUST.info()

ParserError: hour must be in 0..23: 2020-12-01 24:00:00

In [ ]:
DUST.head(26)

In [3]:
# 데이터 파일 읽어오기 5월
DUST = pd.read_csv('dust/202101dust.csv', encoding='euc-kr')

In [4]:
DUST.head()

,날짜,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,경북,경남,제주,세종
0,2021-01-31,27,28,25,24,32,20,20,29,21,27,31,31,24,19,25,11,28
1,2021-01-30,23,24,25,24,27,20,22,25,20,24,33,32,18,22,22,14,23
2,2021-01-29,9,11,9,10,13,9,8,9,7,9,12,10,10,9,9,10,9
3,2021-01-28,16,18,19,16,21,14,15,16,15,18,19,18,16,17,17,18,17
4,2021-01-27,18,17,20,15,18,19,16,20,16,26,22,20,14,19,14,16,21

In [5]:
DUST.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      31 non-null     object
 1   서울      31 non-null     int64
 2   부산      31 non-null     int64
 3   대구      31 non-null     int64
 4   인천      31 non-null     int64
 5   광주      31 non-null     int64
 6   대전      31 non-null     int64
 7   울산      31 non-null     int64
 8   경기      31 non-null     int64
 9   강원      31 non-null     int64
 10  충북      31 non-null     int64
 11  충남      31 non-null     int64
 12  전북      31 non-null     int64
 13  전남      31 non-null     int64
 14  경북      31 non-null     int64
 15  경남      31 non-null     int64
 16  제주      31 non-null     int64
 17  세종      31 non-null     int64
dtypes: int64(17), object(1)
memory usage: 4.5+ KB

In [6]:
DUST.head()

,날짜,서울,부산,대구,인천,광주,대전,울산,경기,강원,충북,충남,전북,전남,경북,경남,제주,세종
0,2021-01-31,27,28,25,24,32,20,20,29,21,27,31,31,24,19,25,11,28
1,2021-01-30,23,24,25,24,27,20,22,25,20,24,33,32,18,22,22,14,23
2,2021-01-29,9,11,9,10,13,9,8,9,7,9,12,10,10,9,9,10,9
3,2021-01-28,16,18,19,16,21,14,15,16,15,18,19,18,16,17,17,18,17
4,2021-01-27,18,17,20,15,18,19,16,20,16,26,22,20,14,19,14,16,21